### ISSUE TITLE
[Items] Custom mob drops vanish.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#102]
Currently i disable normal mob drops and then set my own drops.

After killing a mob whatever is dropped is correct but if you kill multiple mobs and pick up one of those items the rest are deleted.
This only affects drops that i changed and not normal drops.

If a mob drops different items only the one you pick up will disappear but if you try to pick up the others it will do the same.

**Comment by Lycanite** [comment]
Hmm sounds like the items are dropping on the client instead of the server side, I'll take a look into it!

**Comment by Claycorp** [comment]
Its not likely client side as you can pick up one item before the others are deleted and it doesn't matter what one it is.

**Comment by Claycorp** [comment]
So is there any progress on this? Its kinda a big deal. Like game breaking.

**Comment by Lycanite** [comment]
I'm going to be working on an update soon fixing a few bugs and adding some new features.

**Comment by Claycorp** [comment]
6 months almost and still no fix yet you added a crap ton of other stuff in between? C'mon man.... I typically don't push for fixes but I quit working on a project because of issues and would hope that in a few months things would be better and I see this still isn't fixed....

**Comment by Lycanite** [comment]
Released new update, fixed: http://lycanitesmobs.com/update/1.13.0.4
