### ISSUE TITLE
Immortal Falling incompatibility bug

### ISSUE THREAD

**Issue by BLSK** [Lycanite/LycanitesMobs#106]
Hello both @Lycanite and @WayofTime,

I am the constructor of the modpack PVPE and both Blood Magic and Lycanite Mobs are in it.
I turn out to be immortal to fall damage when 'only' your two mods are present, and when the pack is fully intact.

Method of Testing:
Take Fatal Fall damage the first time, You die
Take Any fall damage after first death and you take no damage and can't die from it.
Effective: Both Server and Client

It was something I stumbled on testing out fixes of other mods that crashed client and/or Server on 'deaths'  Fall deaths was easily test.  I still seem to take damage from other sources but not all are tested.

I am using both your latest versions
BloodMagic-1.3.3-4
LycanitesMobsComplete 1.11.0.1
Forge 1403

**Comment by WayofTime** [comment]
Any potion effects active? I have a feather fall potion effect, you may have a potion id conflict. That would be the only reason on my end.

**Comment by BLSK** [comment]
So if I understand:
It could be an effect a mob is able to utilize, that was added in more recent builds...  I could try to narrow down the mob(s) in question if it were help.  I am just unsure how a player spawning for the first time in the world with nothing, would gain such ability after first death from fall damage and never achieving anything.  Oh this shouldn't be fun XD.  Considering how many mods in this day and age that potentially negate fall damage, it may of been around for a while...

I may ask is there a method of disabling potion effects in Blood Magic or Lycanite?
I'll try and narrow down which Lycanite and Blood Magic first came up with the issue.  If it was just a new mob in Lycanite, perhaps if I disable it, it would void the issue.

anyways...

sadly with this bug, I have to choose which mod must take a backburner... if I find a reason for it, it might be able to be disable.  I will do more investigation.

**Comment by WayofTime** [comment]
Not quite, really. Lycanite mod should have a potion id map in the configs. To confirm if this IS the issue, check my config and move the potion id for the feather falling. If it stops, that is the issue. Shouldn't need to decide.

**Comment by BLSK** [comment]
To confirm,  Lycanite Mobs after some extra testing, now has your ID for Fall Resist which is 114.
I took a few more deaths to verify but since found the Fall Resist and moved it to Blood Magic's ID I do die now.  I appreciate the information @WayofTime.  I just hope it doesn't bug out something else... wasn't able to disable either, but yeah... thanks

**Comment by Lycanite** [comment]
Ah yeah I did end up created a potion effect to grant fall resistance, this is only really used for players dismounting Striders as they are very tall!
