### ISSUE TITLE
[Achievements] Warg Tooltips

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#112]
Slay warg and add a warg to bestiary have the same hover tooltips.

Thats pretty dam good for the amount of copy/paste/edit that is.

**Comment by Lycanite** [comment]
Oh thanks for pointing that out! XD
Yeah I normally copy and paste the lang entries a lot and then go through and edit them. Some had typos too but I think I've fixed all those now!

**Comment by Claycorp** [comment]
Yeah im no spell checker. :P

**Comment by Lycanite** [comment]
This will be fixed in the next update: 1.11.0.6.
