### ISSUE TITLE
Server Crash in player logging

### ISSUE THREAD

**Issue by Bogdan-G** [Lycanite/LycanitesMobs#118]
Hello, SpecialMobs 3.1.1, SpecialAI 1.1.1, Lycanite Version 1.11.0.5, Forge 1492 (server and client)
Server Cauldron 1492.150
Server normal start, but any player login and crash:
https://gist.github.com/Bogdan-G/9d8b51c1085a32213afe
https://gist.github.com/Bogdan-G/482cb01e01594da0e0de

configs SpecialAI, SpecialMobs, LycaniteMobs: https://yadi.sk/d/vAWWYLVviKD7h

**Comment by Lycanite** [comment]
This looks like a bug with SpecialAI:
at toast.specialAI.ai.special.EntityAIThief.func_75246_d(EntityAIThief.java:143)
Here it is trying to treat a Vespid like a player which causes the crash.
I'll link Toast to this.

**Comment by Bogdan-G** [comment]
SpecialAI since then has not been updated, and the bug was.
