### ISSUE TITLE
Request - Needs additional Thaumcraft Support

### ISSUE THREAD

**Issue by DPxKnightxZero** [Lycanite/LycanitesMobs#120]
Some people of my server claim the essence drops are failing I am using the latest release. Just letting you know incase others have hinted at it.

**Comment by Lycanite** [comment]
I currently don't support any mods such as Thaumcraft but I do have big plans too in the future such as turning each Scepter in a Wand Focus, etc. For now though it's a matter of having the free time to do things like this! XD

**Comment by DPxKnightxZero** [comment]
Really? Just allow essence drops XD make it random at least my players will shut up :D

**Comment by Lycanite** [comment]
I'll need to pull in the Thaumcraft or Baulbles API, find which method(s) I need to use and then add a conditional part to my mob creation process that checks for Thaumcraft and assigns essences.

**Comment by Lycanite** [comment]
With the move to 1.9 I'll wait and see what Thaumcraft is like. In the mean time I believe there is a mod that adds essence drops to Lycanites Mobs now.
