### ISSUE TITLE
Bug - the spriggin vampire affect is greatly ineffective

### ISSUE THREAD

**Issue by DPxKnightxZero** [Lycanite/LycanitesMobs#122]
So I used to fear spriggins but in the latest release lets be serious ... they are pussies. They die in one hit and even when surrounded they die without posing much of a threat. It sucks to ask but is that intended?

**Comment by Lycanite** [comment]
Lol, dat pun doh!

I'll strengthen them back up, they were recently nerfed but I think a lot of players aren't using axes against them so I might need to make that clearer!

**Comment by DPxKnightxZero** [comment]
Heheh I love your mod its deliciously sadistic :D I am going to created you for the creation of this outwork since your mod as long as you make sure it remains 1.7.10 stable for me ;P and make 1.9 when it is released because lets be honest 1.8 adds almost nothing XD some devs refuse to understand that XD Anyways thank you :)

**Comment by Lycanite** [comment]
Good news! Lycanite's Mobs for 1.9 is out! :D 
I'll have to look back into Spriggan health regen what with the new 1.9 combat being a bit slow and more thought out.
