### ISSUE TITLE
Tinkers tool issue with Geo's.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#126]
Something seems to be wrong with the checking of tool type.
You can't kill a geo with anything but a hammer and an axe(hatchet). Everything else will not harm it.
EDIT: I should have checked with the new version ill test with that real quick too.
EDIT 2: Still is an issue on the latest update.

**Comment by Lycanite** [comment]
Hmm I'll take a look!

**Comment by Servovicis** [comment]
Any word on this? Geo's don't take any damage from tinkers picks. Hammers, axes and swords work though.

**Comment by Sir-No** [comment]
i found out that flint pickaxes in tinkers only have an attack of +3. The defense of geos completly nullifies it (geos defense is 4, so damageAfterDefense uses 3 - 4 = -1 and returns 0 if that is negative). The damage multiplier of the pickaxe (which is 4 times the normal dmg) gets only calculated after damageAfterDefense is calculated, which results in 4*0 = 0.

One option to fix it would be to change the geos defense to 2, but half the damage multipliers. Weapons that do less than 6 attack will be slightly buffed against them, the ones with 6 will do the same dmg and the ones that do more will do less damage.
Another way is to change the order of getDamageAfterDefense and getDamageModifier in the attackEntityFrom function in /lycanite/lycanitesmobs/api/entity/EntityCreatureBase.java . The problem with this is that it will change how hard it will be to kill other mobs with damage multipliers...

**Comment by Badcholo** [comment]
Why are you using such a weak pickaxe to fight mobs? Get a Sword, or in my case. A Gun.

**Comment by Claycorp** [comment]
Because not every pack and mod is made exactly the same? The way the math is done doesn't work well with everything especially tinkers. It would be much better if it was set up to do a minimum damage if it's a pickaxe instead of a bonus. You could also do a bonus plus a minimum damage plus half the pickaxes damage. There is a few ways to go about this but the one used is the worst of them all because it can result in no damage even when using 'the appropriate tool'.

**Comment by Badcholo** [comment]
Well, it makes sense to me that if wear armor or if your skin is hard that you take no damage from junk tools or weapons. Plus modpacks have nothing to do with with this issue, vanilla itself has better weapons unless your pack plans on removing diamond or iron tools. Everyone always goes to the top tier weapons and tools anyways. Your modpack sounds like it sucks if you have to use a flint tool. You might as well cry that you don't do a +1 damage to a mob with defense 4, cause you want to fight with your hands.

**Comment by Servovicis** [comment]
The issue isn't that a +3dmg pick does no dmg to a mob with 8 armor. the issue is a +3 dmg weapon isn't taking into account the bonus dmg modifier to the mob. That isn't a vanilla issue but an issue with the damage math. Why not state something towards the issue rather then flaming the OP about how its not. Badcholo, if you dont want to talk about THIS issue, find a different thread.

**Comment by Claycorp** [comment]
Sorry @Badcholo that other people think differently than you. Minecraft has tons of mutations of play styles and this error is something that doesn't allow people to play in those styles because the math is done poorly.

Also Currently in 1.7.10 tinkers is one of the most popular tool mods out there. Along with its tweak mod, Tinkers tweaks. You think that people would be willing to fix an issue that affects something that popular and typically they are if given the correct information and a possible way to fix it.

This is why Git issues and constructive criticism exist. I found an issue, People looked into it deeper found the problem and we gave possible options to fix it. Now its up to lycanite to say if he is/is not adding/changing it. Flaming me gets you nothing other than looking like a fool.

**Comment by Badcholo** [comment]
I know tinkers, and i don't see why you keep crying about one of it's weakest tools buffed up that does no damage. My input was to hopefully stop you from wasting peoples time, but again it is up to lycanite if they choose to fix this. Hopefully next time you won't come back crying about not causing any damage when you hit it with a stick. I have actually had to increase their health 100 - 500 hp just to make it challenging, cause the default was just ridiculously easy.

**Comment by Claycorp** [comment]
You obviously don't know. I would love to see you play any sort of hard pack that uses tinkers with tinkers tweaks.

Your input is nothing but whining about people talking about an issue. I'm glad you make the modding community such a nice place to work with others.

I'm glad that you play with Draconic Evolution and other ridiculously OP mods and that you needed to change something. Totally applies to the current conversation about how the math is done.

**Comment by Servovicis** [comment]
Again the issue is not about the picks not doing damage. as most picks do less then 8 damage, it all gets nullified by armor before the modifier gets applied. so instead of a 3 dmg pic, like my obsidian pick, doing 3*4-8 dmg(4 dmg) it does none. even my wooden vanilla pick does more dmg...

**Comment by Badcholo** [comment]
I play Hard Vanilla.

**Comment by Lycanite** [comment]
I finally found the cause to this! A mob's defense stat was being applied to the incoming damage before the damage multiplier which meant a pick doing say 4 damage would be reduced by a Geonach's 4 defense down to 0 which is then multiplied by 4 because it is from a pick but 4 x 0 = 0, with it the correct way round the incoming damage is multiplied first (4 x 4 = 16) and then reduced by defense (16 - 4 - 12) dealing a massive amount of damage instead of no damage for very little damage!

This is fixes the 1.14.0.0 Beta06 build for Minecraft 1.9, I'll likely go through the 1.7.10 build at some point and apply some of the 1.9 fixes.

**Comment by Servovicis** [comment]
That indeed was the case. Thanks for the 1.9 update fix. Looking forward to a potential 1.7 fix too! Keep up the excellent work you do with this mod. (I'm a fan of high config options)

**Comment by Claycorp** [comment]
You were told the cause of it back in February in this issue by Sir-No? Not sure how you are just now figuring it out....

**Comment by Lycanite** [comment]
Oh wow sorry Servovicis, I totally didn't see that message! Thanks man! I was on hiatus a bit at that point in time and just came across the issue when updating to 1.9! XD

**Comment by Claycorp** [comment]
You goof. Anyway hope to see the 1.9 fixes backported to 1.7.10 if possible!

**Comment by Lycanite** [comment]
XD Once I get everything updated to 1.9 I'll jump back to 1.7.10 for a final update to fix these things.

**Comment by Claycorp** [comment]
Aight. Looking forward to those fixes in 1.7.10! Thanks! (Hopefully soon 1.9 will be getting a bit more stable and people can finally move on XD)

**Comment by Servovicis** [comment]
Def glad to see more mods slowly making their way to 1.9
