### ISSUE TITLE
Random user data loss

### ISSUE THREAD

**Issue by Vorquel** [Lycanite/LycanitesMobs#127]
Sometimes when I go to check on my bestiary, mounts, or other related menus, I find that all my gathered knowledge and/or tamed beasts have been lost.

**Comment by Lycanite** [comment]
This has been fixed in the latest update 1.13.0.5. :)
There is also sometimes an issue when switching dimensions, but the loss shouldn't be permanent and it is just the client side going out of sync.

**Comment by Vorquel** [comment]
Thank you for your response. I will use the new version and let you know if any problems arise.
