### ISSUE TITLE
Crafting pure lava duplicates bucket

### ISSUE THREAD

**Issue by Vorquel** [Lycanite/LycanitesMobs#128]
Crafting was done in the player inventory with these mods installed:

Applied Energistics 2 rv2-stable-10
Brandon's Core 1.0.0.10-bugfix
CodeChickenCore-1.7.10-1.0.7.47-universal
CoFH Core 3.0.3
Draconic-Evolution-1.7.10-1.0.2-Snapshot_7-bugfix
Extra Utilities 1.2.12
Inventory Tweaks 1.59-dev-152
Lycanites Mobs 1.13.0.5
MachineMuse's Modular Powersuits 0.11.0.284
MapWriter 2.1.10
McJtyLib 1.8.0.n32-SNAPSHOT
NotEnoughItems-1.7.10-1.0.5.118-universal
Numina 0.4.0.119
RFTools 4.13
Thermal Dynamics 1.1.0
Thermal Expansion 4.0.3B1
Thermal Foundation 1.2.0

**Comment by Lycanite** [comment]
Oooh, I shall take a look into this one!

**Comment by Lycanite** [comment]
I'm uploading 1.14.0.1 shortly which will have a new shaped recipe:
# = Air, I = Iron, M = Magma Cream, G = Ghast Tear
#G#
IMI
#I#

I'll fix the lava bucket based recipe later.
