### ISSUE TITLE
Flans mod crash

### ISSUE THREAD

**Issue by mensreaMC** [Lycanite/LycanitesMobs#130]
Whenever a vehicle from Flans mod is placed in the world I get the following error.

http://pastebin.com/7JSDye7x

This is with the most recent version of Lycanites. I'm not sure if this is a Flans issue or not, but figured you would be the best person to ask.

**Comment by Lycanite** [comment]
This might be on my end, I'll take a look!

**Comment by Badcholo** [comment]
Were you able to place vehicles before lycanites mobs? I see so many crashes from vehicles because they need the correct dependencies.

**Comment by mensreaMC** [comment]
Yes, and just to make sure I tested it again just now. I can place vehicles without the game crashing by removing only lycanites.

**Comment by mensreaMC** [comment]
Ok, I did some more testing and I discovered the same bug in the previous version 1.13.0.4. However, in that version, the bug just gives you a fatal error and kicks you out of the game instead of crashing to desktop. I have the crash related info here: http://pastebin.com/i3M4jEry .

**Comment by mensreaMC** [comment]
Did anyone ever determine what was causing this?

**Comment by Lycanite** [comment]
This bug was related to how extended entity logic worked, in forge for 1.9 this is all done in a new way that should prevent crashes like this one, I can't really do much about 1.7.10.
