### ISSUE TITLE
Mob position constantly resetting.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#131]
Whenever some mob are idle and just rotating/looking around every few seconds they all snap back to a 'default' rotation. It seems to be the last position they were looking in after they stopped moving.

It looks awful when there many mobs on screen just constantly rotating and snapping back over and over again. Most noticeable in large passive mobs as they are idle the most.

**Comment by Lycanite** [comment]
Hmm this might be related to another problem I'm having with Cacodemons and their jaws as well, I'll take a look!

**Comment by Lycanite** [comment]
The AI improvements in the 1.9 releases have fixed this bug.

**Comment by Claycorp** [comment]
Will 1.7.10 be seeing a fix for this?

**Comment by Lycanite** [comment]
I'll make a note to look into it for 1.7.10 when doing various other fixes too.
