### ISSUE TITLE
Silex drops far too much lapis.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#132]
There is no real point in mining for lapis go to any near by medium to large water source and you can get stacks of lapis. Fortune just makes the issue worse. Subspecies drop near a stack per kill with looting 3.

In all honesty it's silly the amount of lapis you can get from these things.

**Comment by Lycanite** [comment]
I'll look into lowering the default amount, in the meantime you can set custom drops via the freshwatermobs-general.cfg config with the default drops disabled.

**Comment by Lycanite** [comment]
In updating 1.14.0.1 which i will be uploading shortly, Silex will now drop 2-6 Lapis down from 6-16 as well as 1-2 silex meat down from 1-5.
