### ISSUE TITLE
crash when opening the summoning pedestal

### ISSUE THREAD

**Issue by Badcholo** [Lycanite/LycanitesMobs#134]
http://pastebin.com/pnsJJE0z

I opened the summoning pedestal and pressed a button and crashed.

**Comment by Lycanite** [comment]
Thanks for the crash report, it's hard to pin down what's going wrong from it though. Are you able to repliate this every time, if so what are the exact steps?

**Comment by Badcholo** [comment]
After hours of configuring the mobs, health, spawning, ect. I have finally finished. I have uploaded the mod to the server and modpack and am going to finish testing this crash on the server, without optifine, but it doesn't seem like that would cause this type of issue. Any idea on what may have caused this?
I attempted to open the pedestal and pressed some buttons. I can't remember what i was holding, it was very quick, i will try to replicate it.
if your interested to see, it's here: http://www.technicpack.net/modpack/hardvanilla.779656

**Comment by Badcholo** [comment]
it comes with the server ip installed.

**Comment by Lycanite** [comment]
Ah looks like a pretty decent pack! :D 
I'm not too sure what could be causing it, all the bug report tells me is that there's an issue with a block placement network packet but it doesn't specify and further details really.

**Comment by Lycanite** [comment]
On my journeys from 1.7.10 to 1.9 I learnt that network packets run on a different thread which may cause issues. In 1.9 builds this hopefully wont happen now as I have made the packets call the main thread when interacting with the world.
If this crash happens in 1.9 builds from alpha 05 onwards please open up a new issue and I shall investigate further.
