### ISSUE TITLE
Feature Suggestion: No knockback

### ISSUE THREAD

**Issue by Badcholo** [Lycanite/LycanitesMobs#135]
On my server i have removed knock back from all mobs, even from flan's mod thru plugins.
The mobs from your mod still take knock back for some reason. Would it be too hard for a config option to remove knock back? I can hold back mobs and it's just too easy to kill them even with 500 health on the mobs. I am only wearing diamond armor. I really didn't want to increase the mob damage, cause players will complain about being 1 shot. I think this way is the best way to increase difficulty. It has gave my server better fights with mobs, bosses, and pvp, specially since flan's guns don't launch you into the air anymore.

**Comment by Lycanite** [comment]
I can look into implementing a global config option for this, would this be the player receiving knockback from monster attacks or monsters receiving knockback fro player attacks, or config options for both?

**Comment by Badcholo** [comment]
both

**Comment by Lycanite** [comment]
The recent 1.9 releases have reduced knockback also the 1.9 combat changes make fighting much more challenging and interesting, I'll still look into adding a no knockback config for 1.9 though.

**Comment by Lycanite** [comment]
I've decided not to implement this can it can be tricky to add and doesn't look like a good idea for the new combat system anyway.
