### ISSUE TITLE
Bug - Lycanites Mobs being pulled 1 direction.

### ISSUE THREAD

**Issue by PepeEconomics** [Lycanite/LycanitesMobs#137]
In my minecraft, (which is running around 100 or so mods) lycanine's mobs and only lycanine's mobs are being pulled slowly (or quickly) towards 1 direction. It isn't lag, as I can still hit and damage these mobs. The effect goes away when they aggro on something.

**Comment by PepeEconomics** [comment]
I found the problem! For some reason llibrary is making lycanites mobs freak out.

**Comment by Lycanite** [comment]
Ah strange, ah well, I'm glad you found the problem!
