### ISSUE TITLE
Important Request - Support for reverting poisoned mca family memeber when the dead at your door event plays.

### ISSUE THREAD

**Issue by DPxKnightxZero** [Lycanite/LycanitesMobs#139]
I have a lot of players getting upset with me about their kin being turned into ghouls during the dead at your door event. Is there a way you can either make the event ignore tamed MCA mobs or give players a way to revert the changes? Oh yeah and thank you for increasing the grue and such.

**Comment by Lycanite** [comment]
Ghouls and Crypt Zombies have the same logic as vanilla Zombies when it comes to turning villagers, I think it's on a killing blow that, but I'm not certain.
Either way, in the lycanitesmobs-general.cfg config there is an option to stop monsters from targetting villagers, this includes MCA villagers.

**Comment by DPxKnightxZero** [comment]
Thank you very much for your response I will look into changing that then.

**Comment by Lycanite** [comment]
No problem! :)
Let me know if you come across and issues!

**Comment by DPxKnightxZero** [comment]
I would like you to start a 1.8.9 branch since they had a stable release I promise to test the hell out of it ;P

**Comment by Lycanite** [comment]
I would like to but it's going to take a lot of time, and once it's at the stage of being testable, most of the work is done, beore that stage the game wont even launch. The major problems with 1.8.9 are the likes of the massive amounts of JSON needed just to add blocks let alone entire entities. I might hold back until 1.9 instead as apparently some changes from 1.7.10 to 1.8.9 may be reverted.

**Comment by Badcholo** [comment]
Yeah, i'm waiting for 1.9 to start up a new modpack / Server as most people are doing.

**Comment by Lycanite** [comment]
Seems to be the way to go. :)
If only Notch stuck to his work and released Minecraft as open source instead of selling it to Microsoft, open source Minecraft would be amazing! Ah well!
