### ISSUE TITLE
Client Crash 1.7.10 Rendering entity in world ISE Already Tesselating!

### ISSUE THREAD

**Issue by plazia** [Lycanite/LycanitesMobs#140]
Crashlog http://pastebin.com/NPAf5GQ7

**Comment by Lycanite** [comment]
Hmm strange, are you running any other mods and can you replicate this consistently?

**Comment by plazia** [comment]
Not to worry I was running Optifine and turning off certain options like multi-core chunk rendering seems to have eliminated most of my crashes. So perhaps it was nothing to do with Lycanites Mobs and everything to do with Optifine. My apologies.

**Comment by Lycanite** [comment]
Ahh I see, yeah maybe changing the options affected the tessellated where it wasn't closed in time or something! XD Let me know if the problem persists though.
