### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by O13SC3N3** [Lycanite/LycanitesMobs#141]
Forge 1614
Mc 1.7.10
Mod Version: 1.13.0.5

http://pastebin.com/0fU1Cfrz
and
http://pastebin.com/raw/pV3cTXHy

Warg is catchable, You can place a saddle on it, But soon as you mount it server crashes, when player logs in (acts as mounted) crashes again.

**Comment by Lycanite** [comment]
It looks like the custom potion effects are being broken by another mod. The Barghest will apply various buffs to it's rider using custom potion effect IDs but unfortunately some mods don't implement potions in a way that is friendly to other mods which causes a crash like this one.

Via the general config you can disable all custom potion effects added by Lycanites Mobs which should stop the crash, if not you'll need to track down the mod that is messing with the effect ID list and from there try to stop it. You can also manually assign all custom potion effect IDs for Lycanites Mobs via the config too.

**Comment by O13SC3N3** [comment]
I had that issue with the potion effects before disabling it via config to stop players crashing from example Geonauchs causing the player to crash due to miners fatigue debuff. Not all the mounts have issues. cant tame chcobacobras (wtf ever lol) raptors seem fine just the barghest and warg so far. Pinkys and Crusk cant tame either. If you like id give you the configs to see if I did something wrong?

**Comment by O13SC3N3** [comment]
And what's interesting g iny potion ID list shows lycanites doesn't register anything and the ids are available yet the mobs still apply their debuffs, maybe the setting isn't taking effect? And my previous issue when players get attacked maybe the mobs were trying a double effect? Not sure, I even deleted the config and redid them.

Mobs attacking a player will cause them to crash, disabling the effects fixes this yet mobs still apply the setting as if nothing changed

**Comment by Lycanite** [comment]
Some mobs can only be tamed as babies, that might be the issue there. You could try manually setting potion IDs instead of disabling them. Minecraft 1.8.9/1.9 introduces a proper potion registry which fixes this problem.
