### ISSUE TITLE
altars don't work.

### ISSUE THREAD

**Issue by Badcholo** [Lycanite/LycanitesMobs#142]
I tried to use the altars and...
The Umber lobber altar, destroys the terrain, but does not spawn anything. it just cuts out a section of the ground. The Umber lobber atar states in console that the bounding box is null.
The rohovart altar, builds the lair but rohovart does not spawn.
I'm very surprised cause i haven't found any bugs with the mod so far until now.

this is for rohovart. Entity bounding box null.
I see in console that it states. Entity being removed for bounding box restrictions.
BBsize 17,496 > 1000 avg edge 28.928

I'm using KCauldron-1.7.10-1614.201
it has been pretty stable

**Comment by Lycanite** [comment]
Hmm this is very odd, are mobs allowed to spawn? The altars wont work on peaceful and also other mods that control mob spawning may also interfere as well as changes to the spawning configs of Lycanites Mobs. I'd also check your Cauldron plugins in case any of those are affecting things too such as WorldGuard blocking mobs, etc.

**Comment by Lycanite** [comment]
It looks like a Cauldron plugin might be blocking them from spawning as larger mobs do have larger than normal bounding boxes else they can't be hit correctly.

**Comment by Badcholo** [comment]
I'll do some testing tonight. it works fine in single player.
