### ISSUE TITLE
I broke my API (mobs not in Doomlike Dungeons)

### ISSUE THREAD

**Issue by BlackJar72** [Lycanite/LycanitesMobs#143]
Some people have reported that the mobs no longer appear in the Doomlike Dungeons.  I think I know why -- I broke the API because some suggested that modid should be all lower case.  Then new API version 1.4.1 now looks for both the original and all lower case modids.  Just dropping in the new classes from the jar should work.

(On a related note, whole groups should probably only be added to biome of very closely themed -- having things like skylus in an air fill dungeon doesn't work well....)

**Comment by Lycanite** [comment]
Ok thanks for the info, I'll post an updated 1.7.10 build shortly

**Comment by Lycanite** [comment]
I'll be uploading a fixed 1.7.10 build soon, is the API unchanged in 1.9 as I'll be releasing beta builds out very soon!

**Comment by Lycanite** [comment]
I've updated the latest 1.9 builds to fix this, I'll update 1.7.10 later on too.

**Comment by BlackJar72** [comment]
OK, sorry I've not been answering; my internet's been down.  Sounds good.
