### ISSUE TITLE
[1.9] Mobs are sometimes transparent

### ISSUE THREAD

**Issue by Vorquel** [Lycanite/LycanitesMobs#144]
Mods installed:
Forge build 1891
Inventory Tweaks 1.61 dev 49
Journey Map 1.9 5.2.0b1 unlimited
JEI 1.9 3.3.3.197
JER 1.9 0.4.5.25
Lycanite's Mobs Complete 1.14.0.0 ALPHA
Mantle 1.9 0.9.4
Pam's Harvestcraft 1.9a
Tinkers Construct 1.9 2.2.2

**Comment by Lycanite** [comment]
I've noticed this too, I'm not too sure what it could be just yet though. Thanks for reporting!

**Comment by Lycanite** [comment]
I think I've managed to fix this one, let me know if it happens again. Fix is in alpha02 I think if not definitely in alpha03 which I'll release in about an hour or so.
