### ISSUE TITLE
Server Crash 1.9

### ISSUE THREAD

**Issue by Badcholo** [Lycanite/LycanitesMobs#146]
Used the latest forge 1.9 1893. Lycanites Mobs 1.14.0.0 ALPHA04
http://pastebin.com/bz96VD6b

**Comment by Lycanite** [comment]
Hmm it looks like it could be related to mob armor values or something like that, I'll do some digging around.

**Comment by Lycanite** [comment]
Some client side code was being called on the server, will be fixed in alpha 05 thanks for the bug report!
