### ISSUE TITLE
lycanites-mobs-1.9-1.1.4.0.0-beta03 crashes dedicated 1.9 build 1904 server during play

### ISSUE THREAD

**Issue by kreezxil** [Lycanite/LycanitesMobs#147]
crash report: https://gist.github.com/d831d22b73e32af19ada670f6a324874

**Comment by Lycanite** [comment]
Oops, there's an annoying issue where getCollisionBounding box and getSelectedBounding box seem to be named the wrong way round, one is for the client side selection box the other for collision, it's an easy fix I'll upload BETA04 to Curse now with the fix.

**Comment by Lycanite** [comment]
http://lycanitesmobs.com/update/1.14.0.0B04
