### ISSUE TITLE
lycanites-mobs-1.9-1.14.0.0-beta04 crashes server

### ISSUE THREAD

**Issue by kreezxil** [Lycanite/LycanitesMobs#148]
crash report: https://gist.github.com/c4255b17e9337ea2f8cef361f90c04e6

Apparently happens when the player encounters w/e the scorchfire is

**Comment by Lycanite** [comment]
Yeah I messed up and made it so Scorchfire can randomly age past a metadata of 15! XD
I've already got this fixed in my dev build though and I'll be posting the next release in a couple of hours or so with the Arctic Mobs added back too!
