### ISSUE TITLE
[1.9.4] Server Crash

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Lycanite/LycanitesMobs#149]
One of those things that flies out of rivers was attacking me and this crash was produced.
(Odd Blue spiral thing. Cannot remember the name).
https://gist.github.com/Shadows-of-Fire/18ea22b7185577321549ea444d90d884

**Comment by Lycanite** [comment]
Oops, looks like projectiles are calling a client side only method, it's a super easy fix I'll release an update later today for 1.9 and 1.9.4.

**Comment by Lycanite** [comment]
Should be all fixed up now! :)
