### ISSUE TITLE
[1.14.0.3] Only Alphas Spawning

### ISSUE THREAD

**Issue by OhiraKyou** [Lycanite/LycanitesMobs#150]
I deleted the previous 1.9 version and its config folder before installing 1.14.0.3 in 1.9. Then, I created a world with the name and seed "Dungeon Search" with Doomlike Dungeons 1.8.11-MC1.9 installed. Only alpha jousts and makas spawned. I didn't check other mobs.

Edit: although not to the same degree, even in the previous version, the frequency of large biomes filled exclusively with alphas seems unintended.

**Comment by Lycanite** [comment]
I've noticed this myself however non-alphas do spawn too, I think it's mainly the vanilla mob spawner being so bad, I've set the weights of non-alphas much higher than that of alphas but the spawner is very unpredictable. I will be adding my own customer spawner to handle this in the future.
