### ISSUE TITLE
Crash with Tinkers Construct steel tool effect

### ISSUE THREAD

**Issue by OhiraKyou** [Lycanite/LycanitesMobs#151]
Minecraft 1.9
Forge 12.16.1.1907 (server)
LycanitesMobsComplete 1.14.0.2

Crash report: http://pastebin.com/5uPYHrC3

Failed server connect or kick error on loading in near a specific erepede: arcticmobs:frostweb id 615, doesn't yield a name. Occasionally says frostfire instead.

After attacking an erepede with a steel pickaxe from Tinkers Construct, which, according to the log, caused the bleed potion effect from the tool's steel head, the server crashed. This happened multiple times. The first time, against a jengu, the problem was solved by restarting the server without Lycanites Mobs and then restarting it again with it reinstalled. Now, after a similar incident, loading the chunk containing this mob consistently causes a crash, even with a fresh character.

Edit: Seemed to have fixed it by removing Lycanites Mobs from the client as well before the restart > reinstall > restart loop. Should have thought of that to begin with.

**Comment by Lycanite** [comment]
It looks like the crash is on TC's side as it's just a mob referring to onLivingUpdate() which then acts through vanilla code from there. I'll double check things on my end though and let me know if the TC dev finds it is my end and I'll fix what I need to from there.

It looks as though TC is calling client side only classes on the server side, does this happen with any mob including vanilla mobs or just Lycanites Mobs?

The exception is this: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient which is called by Tinkers COnstruct.

**Comment by OhiraKyou** [comment]
Thanks for looking into it. It appears the TC devs may have already fixed it on their side shortly after your reply; new hotfix for servers crashing.

**Comment by Lycanite** [comment]
Oh nice! Let me know if anything else occurs!
