### ISSUE TITLE
Pure lava not producing new source blocks

### ISSUE THREAD

**Issue by OhiraKyou** [Lycanite/LycanitesMobs#152]
What I've read about pure lava suggests that it is intended to create additional source blocks like water. However, when placing pure lava in a 3x3 ring, the center block does not create a source block in the center.

**Comment by Lycanite** [comment]
Ah thanks for posting this, I'll take a look!

**Comment by Lycanite** [comment]
This will be fixed in the next update 1.14.3.3.
