### ISSUE TITLE
[feature request][mobs] mob scaling factor

### ISSUE THREAD

**Issue by Cat09** [Lycanite/LycanitesMobs#153]
Dear Lycanite,
   this is related to issue #133 
The size of many of the mobs in this mod is really too much for me, (also suffocation damage, but that's a bit of another issue) and I'd like to be able to:
A: see in config what size mobs are, and
B: be able to adjust it

I don't really know hows easy this is to do, especially depending on the ability to scale hit/bounding boxes along with model render size, but it's something I'd really appreciate.
   I Thank you for your consideration, Cat09.

**Comment by Lycanite** [comment]
Currently all mobs have a built in sizing method which I've made very accessible, adding a config that will apply another scale on top of it should be fairly straight forward, I'll look into adding it for you!

**Comment by Cat09** [comment]
thank you very much! I really would like to play with many of the creatures you've created, but the scaling is holding me back on some of them.

**Comment by Lycanite** [comment]
I can understand, I aim to make Lycanites Mobs highly configurable so that it's suitable for more people. In the meantime you can disable individual mobs via the -general.cfg configs.

**Comment by Lycanite** [comment]
Added in 1.16.2.2!
