### ISSUE TITLE
[Question][1.9.4] Does frostfires have a lifetime?

### ISSUE THREAD

**Issue by JCMais** [Lycanite/LycanitesMobs#159]
I could not see they disappearing after some time, do I really need to get rid of them?

**Comment by Lycanite** [comment]
They do have a lifetime but are permanent on Ice and full snow blocks.

**Comment by kinggoesgaming** [comment]
Does that stand true for packed ice and frost block?

**Comment by JCMais** [comment]
hm I might be wrong but I don't think they were being removed after some time if over dirt in a server I was playing, that was using latest version for 1.9.4. Forge was 12.17.0.1976.

As I don't think I will have time to test that this weekend, feel free to close the issue if you think they are correctly being removed.

**Comment by Lycanite** [comment]
I've tested it and all seems to be fine, feel free to open a new issue if they seem like they're too much.
