### ISSUE TITLE
Idle Animation Glitch

### ISSUE THREAD

**Issue by LakMoore** [Lycanite/LycanitesMobs#165]
See in the video here: https://youtu.be/E4aewRu047c

The mobs seem to like spinning while idling, which (if they spun slowly back) would be OK on its own... but they don't.  The glitch back to where they started from.  Also, they seem to do it in unison rather than each being at a different point in the animation sequence.

Can anyone work on fixing this?

**Comment by Lycanite** [comment]
Hmm I've noticed this too, I'm wondering if they're try to path to somewhere or something. I'll look into it, thanks for reporting the bug and posting a video too.

**Comment by Lycanite** [comment]
I've implemented all of these fixes that are applicable in 1.10+in 1.16.2.2.
