### ISSUE TITLE
Shade crashing the server

### ISSUE THREAD

**Issue by RylenWolf** [Lycanite/LycanitesMobs#171]
Using Salamander, 1.15.1.1

http://pastebin.com/VkXLRDZL

**Comment by RylenWolf** [comment]
I would like to add that this is a client only crash, the server was running fine.

**Comment by RylenWolf** [comment]
I would also like to point out restarting the server fixed this issue, but I still feel like it may be important to check out.

**Comment by Lycanite** [comment]
Looks like this is the same as this: https://github.com/Lycanite/LycanitesMobs/issues/173.
This should be suppressed in the next update (1.15.1.3). :)
