### ISSUE TITLE
Compatibility with modular power armor? please? :C

### ISSUE THREAD

**Issue by lightning02** [Lycanite/LycanitesMobs#172]
Hello, I would like to kindly ask if there was the possibility to raise a compatibility with modular power suits, expecially for 1.7.10, since your mobs bypass that armor. I know it would not be your business at all, but the actual dev of modular power suits has too much work to make it on his own, it would be really nice if you could help him someway, for exampe with a pull request or anything...
Thanks alot for the attention!
https://github.com/MachineMuse/MachineMusePowersuits/issues/729

**Comment by Lycanite** [comment]
The armor bypass is the piercing feature of Lycanites Mobs which can be turned off in the lycanitesmobs-general.cfg config file by settings the easy/normal/hard piercing multipliers all to 0. It's designed so that part of a mobs attack will always ignore armor rating in order to combat mods that add overpowered amror but I've made sure the option is there to turn it off for setups that don't really need it.

**Comment by lightning02** [comment]
Armor bypass is good to keep the game challenging, but, isn't there a feature to simply blacklist the armor or the mod that add particular armor? This would be more customizable

**Comment by Lycanite** [comment]
Hmm I could look into adding that, but it would only be for new 1.10.2+ versions as maintaining older versions is very demanding.

**Comment by lightning02** [comment]
actually the minecraft version with the larger amount of available mods is still 1.7.10, many mods will not even pass through 1.7.10... I know that the forge team force mod developers to push foreward, and is not totally bad, but actually there still is a milestone of modding that is 1.7.10... would be really nice keep a thought at that... naturally after the updates and all the thing needed for 1.10.2+

**Comment by lightning02** [comment]
http://imgur.com/qsVBUTI
By the way I've tryed even what you suggested, with pierce set to 0, but it seems didn't works, it get the same damage even from Wargs or spriggan etc.. do I maybe miss something?

**Comment by Lycanite** [comment]
I've added some additional logic that should completely nullify piercing damage, it will be in the next update (1.15.1.3).
