### ISSUE TITLE
"TREE Player Only" spawn restriction does not work with EnderIO Farming Station

### ISSUE THREAD

**Issue by Hastwell** [Lycanite/LycanitesMobs#174]
On a server running a custom modpack including Lycanite's Mobs v1.15.1.2, EnderIO 3.0.1-86, and Forge 2050 for 1.10.2, Ents from ForestMobs will spawn in significant quantities (900+) in a EnderIO Farming Station tree farm as it harvests trees. This behavior occurs even with B:"TREE Player Only" set to true under lycanitesmobs-spawning.cfg.

**Comment by Lycanite** [comment]
Thanks for the bug report, i'll take a look into it, a fake player might be used but I think there's a way to check for that.

**Comment by Lycanite** [comment]
This will be fixed in the next update (1.15.1.3).
