### ISSUE TITLE
[1.10.2] Crash on LAN/Server

### ISSUE THREAD

**Issue by xlxAciDxlx** [Lycanite/LycanitesMobs#180]
I get a crash any time a Lycanite mob is in close proximity to me. It seems related to #173, but the stack trace is slightly different.

[Crash Log](http://pastebin.com/KUh9ZsL5)

**Comment by Lycanite** [comment]
Is this with the latest update? If it is I'll look into adding a catch for that crash.

**Comment by xlxAciDxlx** [comment]
1.15.1.3, yes.

**Comment by xlxAciDxlx** [comment]
Any ETA on when you'll be able to get the patch out?

**Comment by Lycanite** [comment]
Sorry for the delay! I'll be releasing an update (1.15.1.4) in a few minutes! :D
