### ISSUE TITLE
 java.lang.NoClassDefFoundError: net/minecraft/world/World$2

### ISSUE THREAD

**Issue by MDR-DEV-GIT** [Lycanite/LycanitesMobs#181]
Got a weird bug
https://gist.github.com/MDR-DEV-GIT/aa284242fff734cef4f065ae07f0661e

I was walking in an artic plains. Noticed something odd on my mini-map (it looked like there was a large square block being outlined in the snow on the mini-map). After a bit of walking back and forth trying to see if what the mini map was showing correlated to what i was seeing the game crashed. It said it was trying to tick an articmobs frost cloud 

Forge is 2092 
Lycanite is LycanitesMobsComplete 1.15.1.4 [1.10.2]

**Comment by Lycanite** [comment]
Hmm that is an odd bug, it's like something like a Poison CLoud block or one of the fires as what's happening is it's trying to remove itself (like how fire dies off over time or Poison CLouds fade away after a few seconds) but when it goes to remove itself it can't find a block at its location causing this crash.

A simple check to make the block that is being removed can be found will fix this crash, it's odd how it's happening though.

I'll add this fix into the next update, thanks for reporting the bug. :)

**Comment by Lycanite** [comment]
This looks more like an internal Minecraft or Forge issue as the code calling this is standard. Please reopen if this happens again.
