### ISSUE TITLE
[1.10.2] Crash when Entering Dimension

### ISSUE THREAD

**Issue by xlxAciDxlx** [Lycanite/LycanitesMobs#182]
Any time I try to enter the Overworld (from an RFTools Dimension), my game crashes. Not sure if your mod is the cause (or even related), but figured I'd report it here just in case as the stack trace does mention it.

[Crash Log](http://pastebin.com/iddPsadf)

----
Feel free to delete this if it's not related, as I did find an issue already reported on Mo'Creatures GitHub without the mention of your mod. May just be an odd stack trace goof.

**Comment by kinggoesgaming** [comment]
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
    at drzhark.mocreatures.entity.MoCEntityTameableAquatic.getIsTamed(MoCEntityTameableAquatic.java:87)
    at drzhark.mocreatures.entity.MoCEntityAquatic.func_70094_T(MoCEntityAquatic.java:524)
    at lycanite.lycanitesmobs.ExtendedEntity.onUpdate(ExtendedEntity.java:123)
    at lycanite.lycanitesmobs.EventListener.onEntityUpdate(EventListener.java:192)
```

@xlxAciDxlx bug the MoCreatures developer about this

**Comment by xlxAciDxlx** [comment]
The issue (aside from the mention of Lycanite's Mobs) has already been reported. As stated, I wasn't initially sure which was causing it so I planned to report in both places.

**Comment by Lycanite** [comment]
Ahah! So I have these cast issues all the time, if Mo' Creatures has them too then it might be some kind of forge or even vanilla issue. In the meantime all I seem to be able to do is catch these crashes.
