### ISSUE TITLE
[1.10.2] Entity Data Manager Casting Crashes

### ISSUE THREAD

**Issue by xlxAciDxlx** [Lycanite/LycanitesMobs#183]
I'm either good at finding bugs, or extremely unlucky.. lol Here's another one @Lycanite :)

[Crash Log](http://pastebin.com/SFjd3M9V)

**Comment by Lycanite** [comment]
Thanks! XD
Another casting bug, these are really strange and have only come around on certain server setups since 1.9, I can keep adding catches for these crashes but that's just ignoring the issue, I need to get to the bottom of them lol.

For now I'll go through and add catches to each of these data watcher calls, it looks like a forge issues really but I'm sure other mods that add mobs would be having the same issues so that can't be it.

**Comment by xlxAciDxlx** [comment]
I'm not entirely sure it's a Forge error. Aren't cast errors basically "we want X, but you gave us Y?" Through all the mod updates I've done, this error doesn't seem *too* frequent. Thanks for your hard work!

**Comment by xlxAciDxlx** [comment]
Slightly different crash, more or less posting so you're aware of it (and incase it's not the same cause as above).

[Crash Log](https://gist.github.com/xlxAciDxlx/60dae2ec7e728e6bad06635eaf72bb0d)

**Comment by Lycanite** [comment]
Thanks for the crash log! :) Yeah it's the same casting issue that seems to be plaguing a few mob-related mods. I'll go through soon and catch all these crashes so that the data received from the server is just ignored instead of crashing the client.

**Comment by Lycanite** [comment]
I may have a solution for this coming in the next update 1.15.1.5! :D
I'm leaving this issue open until I can get confirmation!

**Comment by xlxAciDxlx** [comment]
10-4! I'll be sure to throw the update into my test pack once it's out and let you know. :)

**Comment by Lycanite** [comment]
Awesomes, hopefully all will be good, though there is one thing that might fail still, but we shall see! It's tricky as I can't test it easily on my side.

**Comment by xlxAciDxlx** [comment]
That's alright, that's why I test and run "unstable" packs. It ensures everything will get stable quicker.

**Comment by Lycanite** [comment]
Looks like the bug is still going, I know what I missed out though so I'll try and get another update out later today.

**Comment by P3rf3ctXZer0** [comment]
@Lycanite Hey I wanted to let you know something new has been seen in the crash.

Cause: Cutting down a tree
version: Lycanites Mobs 1.15.1.5

Crash Log: https://gist.github.com/P3rf3ctXZer0/98fa775a7ea9a98a2d1e73da475b6e62

Full Log: https://gist.github.com/P3rf3ctXZer0/0aa38285db92f6f38adf80df9fbe2a5b

Extra Notes: [12:33:05] [Client thread/FATAL]: Unreported exception thrown!
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte

**Comment by P3rf3ctXZer0** [comment]
I have finally was forced to remove this mod ... this crash happens way too much ... sorry Lycanite.

**Comment by clifftrials** [comment]
We also had to remove this mod. Will keep an eye for an update. Thanks for all your hard work!

**Comment by Bluexin** [comment]
http://pastebin.com/7iyPA1eu
In case it can help ^-^

**Comment by frenzye** [comment]
another one https://gist.github.com/frenzye/b9151cad053751ea415b9809d40d2a99

**Comment by xlxAciDxlx** [comment]
@Lycanite If you're willing to tell me what needs to be done, I'm willing to make a PR to at least suppress these errors or possibly fix them..

**Comment by Lycanite** [comment]
Hopefully all fixed in 1.16.2.2!
If more casting crashes come up, please open a new issue!
