### ISSUE TITLE
Custom Fire Not Being Removed

### ISSUE THREAD

**Issue by Hastling** [Lycanite/LycanitesMobs#185]
I have "B:"Remove On No Fire Tick"=true" and /gamerule doFireTick false yet fire from Afrit's ect remains in world. If any more information is needed let me know.

**Comment by Lycanite** [comment]
Thanks for the bug report, I'll try and fix this in the next update.

**Comment by Lycanite** [comment]
Looks like when changing to 1.9+ I forgot to re-implement this, will be added as new config options in the next update. For Scorchfire you'll want to look for "Remove Scorchfire on No Fire Tick" in infernomobs-general.cfg.

This will be in update 1.15.1.5 :D
