### ISSUE TITLE
[1.10.2] Concapede Crash

### ISSUE THREAD

**Issue by xlxAciDxlx** [Lycanite/LycanitesMobs#186]
Please don't hate me @Lycanite ... lol

[Crash Log](https://gist.github.com/xlxAciDxlx/6f44ef1d4adaab4058f677e331d964c9)

**Comment by Lycanite** [comment]
Lol there is no hate! The more crash logs the better the updates! :D

**Comment by seanimusprime** [comment]
+1 on this as well. Server starts up fine but when I try to connect with my client it crashes as soon as the world loads due to the concapede's

[Crash Log](http://pastebin.com/G24MM77i)

**Comment by xlxAciDxlx** [comment]
Any word on this, Mr @Lycanite?

**Comment by Lycanite** [comment]
I may have a solution for this coming in the next update 1.15.1.5! :D If the crash persists please open a new issue for it!
