### ISSUE TITLE
Cannot access FTB Friends GUI from inventory screen.

### ISSUE THREAD

**Issue by sharkck** [Lycanite/LycanitesMobs#189]
Whenever I click to bring up the Friends "Teams" GUI to add friends to my claimed chunks, the Lycanites guide pops up instead.  I cannot add my friends to my claimed/loaded chunks because of this.
(The top-left option when in inventory screen)

![screenshot 2016-11-21 00 07 50](https://cloud.githubusercontent.com/assets/960552/20471341/c94bab7e-af7e-11e6-9fe2-a8f417e86ec9.png)

**Comment by sharkck** [comment]
Also, in case this is a bug, theres a green tab in my inventory screen in the shape of a cut emerald? that whenever I hit it, it also brings up the Lycanites guide instead of whatever that tab is supposed to do (assuming that's not intentionally put in by Lycanites).
![2016-11-21_00 05 36](https://cloud.githubusercontent.com/assets/960552/20471292/70b97126-af7e-11e6-97eb-7380ffcc256f.png)

**Comment by Lycanite** [comment]
Hey, thanks for the problem report.
I'll look into this, there maybe just be some kind of GUI button ID conflict, in the meantime you might be able to bind a key to open the menu or you can turn off the Lycanites Mobs Tab button in the lycanitesmobs-general.cfg config file which will likely stop the problem. The Tab on the inventory screen is indeed added by Lycanites Mobs

**Comment by Lycanite** [comment]
I'm closing this as it's quite old now, if the problem still occurs in 1.10.2+ please start a new issue.
