### ISSUE TITLE
[1.10.2] High CPU usage for AI

### ISSUE THREAD

**Issue by cjm721** [Lycanite/LycanitesMobs#190]
Version 1.15.1.4

Was having sever server lag (>100% CPU Core). There was a near linear increase in tick time per person joining (40ms -> 75ms-> 115ms)

Tracked it down to Lycanites via profiling. Bellow is a capture of the troublesome call stack. Disabling Lycanites fixed all the CPU issues (rests around 12ms with 2 players).

![cpuissue](https://cloud.githubusercontent.com/assets/2738614/20496560/c17d73da-aff3-11e6-9443-927e7d056b34.png)

**Comment by Lycanite** [comment]
Thanks for looking this up for me, it looks like the targeting AI is doing too heavy a call when searching for nearby entities (https://github.com/Lycanite/LycanitesMobs/blob/master/java/lycanite/lycanitesmobs/core/entity/ai/EntityAITarget.java#L143) I'll check it with vanilla AI to see if there is a different way it's done now, if not I can always lower the rate that it is called, etc.

**Comment by sharkck** [comment]
Off-topicish... what program are you using to see that?

**Comment by sharkck** [comment]
On topic... I can validate cjm721's findings.  I've been wondering what the heck has been causing such a low tickrate on my overworld.  I found https://www.ej-technologies.com/download/jprofiler/files and it appears to be similar to what he is using (but isnt free!  If you have another program to suggest, please let me know!) and 
![image](https://cloud.githubusercontent.com/assets/960552/20694247/d7cf5928-b5b1-11e6-869c-465c57f04b18.png)

there are my results.

**Comment by sharkck** [comment]
![image](https://cloud.githubusercontent.com/assets/960552/20694414/0128d848-b5b3-11e6-9e60-4c090640454a.png)

**Comment by Lycanite** [comment]
Thanks for the report! I'm going to look at the vanilla mob AI and check it with my own to see what I can do.

**Comment by cjm721** [comment]
@sharkck I am using [jvisualvm](https://docs.oracle.com/javase/6/docs/technotes/tools/share/jvisualvm.html). It is included with standard Oracle JDK (Look in the bin folder for the exe). I don't know if it has any special licensing for commercial / personal use as I use something else at work but since it is included with the JDK I assume free for all use.

**Comment by heyzeusmantoya** [comment]
Any fix possibly coming for this in this version? Modpack I use for my server is 1.10.2 based.

**Comment by Lycanite** [comment]
I hope to fix it soon, I've been busy lately but will be finishing an update for 1.11 (and then 1.11.2) soon as well as bug fixes for 1.10+.

**Comment by heyzeusmantoya** [comment]
Thanks for the update looking forward to it.

**Comment by xlxAciDxlx** [comment]
Any update @Lycanite? Curious to see if this is related to my TPS problems or if I need to report another issue.

**Comment by Lycanite** [comment]
I still need to look further into this, I've been moving home recently so haven't had a lot of time, but once I do I've got a big checklist to go through from fixing that casting issue, then checking this out and then finishing the 1.11 update, I'll get there eventually lol!

**Comment by Lycanite** [comment]
I've made a note to look into this asap, I'd like to fix this and several other bugs before the big 14 new mob update.

**Comment by Lycanite** [comment]
This might now be fixed in 1.16.2.2, I changed the entity searcher to match vanilla, there were a few differences so hopefully this will help.
