### ISSUE TITLE
(Question) Translation for 1.6.4 

### ISSUE THREAD

**Issue by vedroyder** [Lycanite/LycanitesMobs#192]
Hello. I'm a bit slowpoke running 1.6.4, but I realy want to get how to translate this mod into my language to use it at my server.
I'm using lang files from 1.7.10 version, placing them into the same locations in assets, but seems like it doesnt affect anything. Is there anything that I need to change in source?

**Comment by xlxAciDxlx** [comment]
Are you sure the game is set to your language, and not English? Also, double check that your language file and directory are properly named for the language you are using.

**Comment by vedroyder** [comment]
Well, yes, I'm absolutely sure. Here's the resulting jar. As you can see, resources (models, etc) loading properly, but language files are being ignored or something. 
https://www.dropbox.com/s/iauktd0ghbkph4d/Lycanites.jar?dl=0

**Comment by xlxAciDxlx** [comment]
Would you mind either creating a Gist or Pastebin with your language files contents, as well as your console/IDE log?

**Comment by vedroyder** [comment]
Im using ru_RU localisation of this mod, I've just tried to put it into 1.6.4 version of this mod while it was added only at 1.7.10. You can find it in every version of this mod starting 1.7.10.
So my IDE is log here:
http://pastebin.com/n80vcpcz

**Comment by Lycanite** [comment]
I'm not 100% certain, but initially Lycanites Mobs didn't support translations, I may have only added it in 1.7.10, I'll check through the source code to make sure but this is likely the case.

**Comment by Lycanite** [comment]
Looks like translations are only available for 1.7.10 up, I could go back and update 1.6.4 but this is from a very long time ago now and my hands are currently tied with 1.10.2/1.11.2 as well as upcoming 1.12. If I hit a 'resting point' on updates I might look at revisiting older versions.
