### ISSUE TITLE
[Src] Include Gradle, Rename Package Name

### ISSUE THREAD

**Issue by kinggoesgaming** [Lycanite/LycanitesMobs#193]
Currently plain java environment is used with no build system. Although there is nothing wrong with having that, the scope and size of the project has gotten to a point where gradle should be used. Forge provides ForgeGradle for managing forge version, mcmod.info updating and gradle allows running unit tests.

Edit: If you do consider it let me know i can open a PR with the setup

**Comment by xlxAciDxlx** [comment]
The only reason the plain Java environment is used is because if you download this repository, @Lycanite doesn't have the build.gradle/gradle.properties synced to the repository. You can still do everything as you normally would, I'd just think making actual builds isn't possible (which Lycanite can do from pull requests once merged).

**Comment by kinggoesgaming** [comment]
That really shouldn't be a problem as he would just need to delete IDE files and reimport the project

**Comment by xlxAciDxlx** [comment]
Obviously I'm only responding to try and help, so Lycanite's say may be different from mine, but I'm assuming Lycanite has a reason for not having the mod be buildable (though I may be wrong, like I said just trying to help).

I for one would love to have the ability to make builds, even for just testing changes I've made to fix bugs/errors. The only thing I could think of is he'd need to exclude a certain part of the build.gradle if he uses build automation. We'll see what Lycanite has to say though. :)

**Comment by kinggoesgaming** [comment]
I decided to go ahead and do the switch anyways... if you like it you can merge it else it can get a close and be lost in history

**Comment by Lycanite** [comment]
Sounds good, I'll need to get my head around gradle properly, I keep meaning to but just don't have much time at the moment.

**Comment by kinggoesgaming** [comment]
@Lycanite i should target 1.10.x branch right

**Comment by Lycanite** [comment]
I'm going to redo this now that I'm back working on the project again and more aware of everything. I already use gradle, etc but my git repo is set in src/main, I'm going to move it to the project root, sort out a gitignore and then push 1.10.2 and 1.11.2 (master) back up. I'll also move the package name to com.lycanitesmobs as suggested.

**Comment by Lycanite** [comment]
Here's a question, should I use com.lycanitesmobs or com.lycanite.lycanitesmobs?

**Comment by Lycanite** [comment]
Done!
