### ISSUE TITLE
1.10.2 In Game Crash (Client) due to Lycanites and Tconstruct!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lycanite/LycanitesMobs#194]
https://gist.github.com/P3rf3ctXZer0/6c7cafd0ba2e2b35c021a5f140e00765

**Comment by P3rf3ctXZer0** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/2690

**Comment by xlxAciDxlx** [comment]
The casting issues are a known issue (can't find the issue ID to reference atm though), @Lycanite is working on a fix for them but he's been busy lately.
