### ISSUE TITLE
"Disable Spawning" Config Option Not Respected

### ISSUE THREAD

**Issue by xlxAciDxlx** [Lycanite/LycanitesMobs#197]
In the `lycanitesmobs-spawning.cfg` config file, there's the option `Disable Spawning` for disabling all spawns in the mod. Setting it to true doesn't actually disable/disallow the mobs from spawning.

![capture](https://cloud.githubusercontent.com/assets/7502881/21762655/e3fce0b2-d627-11e6-9ec3-7921c7a72508.PNG)

(Sorry for the weird title, couldn't think of a better way to word it xD)

**Comment by Lycanite** [comment]
Thanks for the bug report I shall look into that one, I may have forgot to add the check back in when rewriting my spawners a while ago.

**Comment by Lycanite** [comment]
Fixed in 1.16.2.2!
