### ISSUE TITLE
Fall Damage

### ISSUE THREAD

**Issue by Xee1** [Lycanite/LycanitesMobs#20]
Hi, @Lycanite,  I don't take damage for falling when raiko or similar make me fall.

**Comment by AnonymousPuppy** [comment]
Will this be fixed anytime soon?

**Comment by Lycanite** [comment]
Soon, I've done some things to try and fix it but it's still persisting I'll need to have a good look into it.

**Comment by Lycanite** [comment]
Was finally fixed recently woooo!

**Comment by AnonymousPuppy** [comment]
Awesome :D

**Comment by Xee1** [comment]
Thanks @Lycanite ! Your mod is awesome!
