### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by CrystalNole** [Lycanite/LycanitesMobs#202]
I am currently running a private server for some friends and I installed Lycanites. Occasionally for seemingly no reason. It's about twenty plus lines of this spamming my console and lagging almost everyone out and locking the server for a bit. 

The code is: [lycanite.lycanitesmobs.core.spawning.SpawnTypeBase:spawnMobs:516]: java.lang.NullPointerException

**Comment by xlxAciDxlx** [comment]
Duplicate of #191

**Comment by xlxAciDxlx** [comment]
Sorry, #196 and can't edit my comment on mobile lol
