### ISSUE TITLE
[Items] Scepter Tooltips Show Melee Info

### ISSUE THREAD

**Issue by SargeRyong** [Lycanite/LycanitesMobs#203]
Tooltips for scepters seem bugged.  Lots of extra info that doesn't make sense is added to the tooltips - so much so, that you can't actually see the name or sometimes what the scepter does.  Happens to all "Scepter" items.    

http://imgur.com/U1zwzGz.png

No mods loaded except  for all lycanite's modules.

MC 1.10.2, Mod version 1.15.1.15, Forge 12.18.3.2221

**Comment by Lycanite** [comment]
I need to figure out where this is being set so that I can remove it.

**Comment by Lycanite** [comment]
Fixed in 1.16.2.3!
