### ISSUE TITLE
Geonach spawn causes crash with Extra Utilities 2 Quantum Quarry

### ISSUE THREAD

**Issue by Biochao** [Lycanite/LycanitesMobs#204]
If a Geonach spawns when a Quantum Quarry mines an ore the game crashes.
[crash-2017-01-26_14.43.19-server.txt](https://github.com/Lycanite/LycanitesMobs/files/733459/crash-2017-01-26_14.43.19-server.txt)

Also, as an interesting note while testing this with an RFTools Builder quarry the Geonach spawns and breaks the quarry block and surrounding setup.

**Comment by xlxAciDxlx** [comment]
Is `CROP Player Only` in `lycanitesmobs-spawning.cfg` set to true? If not, try that. Obviously if the config works it won't break the block, but this may also be a bug. I could've sworn it was reported before, but searching for it doesn't return anything.

**Comment by Biochao** [comment]
CROP Player Only is set to true

**Comment by xlxAciDxlx** [comment]
Hmm.. I've heavily adjusted my spawn rates in my modpack, so I'm not sure if they just aren't spawning for me. I'll try with standard configs and see what I can figure out.
