### ISSUE TITLE
Can't disable mobs from spawning on 1.7.10 server

### ISSUE THREAD

**Issue by henrytm82** [Lycanite/LycanitesMobs#207]
I have modified the config file to disable global mob spawning  ("Disable Spawning"=true) and I have disabled WorldGen Spawning ("Disable WordlGen Spawning"=true) and yet I am still getting mob spawns on my multiplayer server.

**Comment by Lycanite** [comment]
I can look into this for 1.10.2 and 1.11.2, if a problem is found I'll make a note for 1.7.10, this version is very old now though and may not receive updates from me, but anyone is welcome to download the code and make a fix.

**Comment by Lycanite** [comment]
Fixed in 1.16.2.2! I will make a note to fix this for 1.7.10 for if I update that version in the future.
