### ISSUE TITLE
Pure Lava not Interacting With Dispensers

### ISSUE THREAD

**Issue by fin444** [Lycanite/LycanitesMobs#210]
I tried to use dispensers to automate my pure lava collection (for TiC smeltery) but unfortunately when it tries to bucket the pure lava, it just throws out a bucket. That also happens when it tries to place the pure lava. (Also, the crafting recipe isn't what it says on the website.)

**Comment by Lycanite** [comment]
I'll look into this.

**Comment by Lycanite** [comment]
Fixed in 1.16.2.2!
