### ISSUE TITLE
Lycanites Mobs spawn even in Mega-Torch area.

### ISSUE THREAD

**Issue by WindRider739** [Lycanite/LycanitesMobs#211]
I've noticed an issue with mobs spawning within the radius of the mega torch from the Torch Master mod. This was used to replace the magnum torch from EU2. There used to be a way to edit this from the general spawning config but I now can't find it. Is this no longer a thing? If not, can it be?

**Comment by Lycanite** [comment]
There's a setting in (I think) lycanitesmobs-spawning.cfg called something like "Ignores Spawn Events" for each of the spawn types listed in there, set it to false to ensure that the spawn event is not ignored, this will allow other mods to cancel the spawning of a mob through the forge spawn event. If the Torch Master mod doesn't use the spawn event then there's not much that i can do on my end though. Hope this helps!
