### ISSUE TITLE
[1.10.2] None of the Age NBT data working with /summon

### ISSUE THREAD

**Issue by qazeral** [Lycanite/LycanitesMobs#212]
Hello!
I'm building a map, where one of the missions is to tame a child mob, which will be your companion for the game, and grow stronger as you play.
I'm using a command block with the /summon command initially. You will be able to pick what pet you will want, and the options would be:
Serpix, Barghest, Ventoraptor, Chupacabra and Cacodemon
Although, Serpix and Chupacabra need to be babies to be able to be tamed.
I used every NBT tag on the /summon command to make them child, and none worked.
/summon *mobname* ~ ~ ~ {Age:0} / {IsChild:1} / {IsChild:True} / {Baby:1} / {EntityCreatureAgeable:1} 
Anyway, is this a glitch or am I who misunderstood the code? If it's me, than does anyone know what should I do?

**Comment by Lycanite** [comment]
Hi!

The baby age acts weird, setting it to -24000 should work for a default baby age.
Basically any negative number is a baby, 0 is an adult and anything above 0 is an adult with a breeding cooldown. These are in ticks where I think 25 ticks = 1 second (I think lol).

**Comment by kinggoesgaming** [comment]
@Lycanite the universal hick unit is 20 ticks = 1 second

**Comment by Lycanite** [comment]
Oops, been a while and I've been Doom modding where it's 35 ticks per second lol!

**Comment by kinggoesgaming** [comment]
Your Tick calculations are DOOMed

**Comment by Lycanite** [comment]
Oooooh I see what you did there!
