### ISSUE TITLE
Infernal mobs: Mobs listing issue.

### ISSUE THREAD

**Issue by Demiosis** [Lycanite/LycanitesMobs#213]
Using: forge-1.10.2-12.18.3.2185

I've listed in Infernal Mob some monster that I wanted to use as Infernal mobs (Also some from ars magica 2).

Ars magica 2 mobs worked fine with the cfgs but a lot of your mobs dosen't seem to be allowed to be boosted as Infernal.

**Comment by Lycanite** [comment]
Could you send me a snippet of the config, just to check that the entity ids are correct. You can find out the entity ids on the website: http://lycanitesmobs.com/creature

**Comment by Demiosis** [comment]
I have added the arix in this list and it does not spawn as infernal and only the other lycanite mobs in this list do. (testes all the spawn eggs with another cfg for infernal that force the mobs to be infernal every time they spawn) and sure,  here's the infernalmobs.cfg:


# Configuration file

entitiesalwaysinfernal {
    B:arcticmobs.arix=false
    B:Blaze=false
    B:CaveSpider=false
    B:Creeper=false
    B:EnderDragon=false
    B:Enderman=false
    B:Ghast=false
    B:Guardian=false
    B:LavaSlime=false
    B:PigZombie=false
    B:Shulker=false
    B:Silverfish=false
    B:Skeleton=false
    B:Slime=false
    B:Spider=false
    B:Witch=false
    B:Zombie=false
    B:arcticmobs.wendigo=false
    B:arsmagica2.DarkMage=false
    B:arsmagica2.Darkling=false
    B:arsmagica2.EarthElemental=false
    B:arsmagica2.FireElemental=false
    B:arsmagica2.Hecate=false
    B:arsmagica2.LightningGuardian=false
    B:arsmagica2.ManaCreeper=false
    B:arsmagica2.ManaElemental=false
    B:demonmobs.astaroth=false
    B:demonmobs.nethersoul=false
    B:demonmobs.trite=false
    B:desertmobs.cryptzombie=false
    B:desertmobs.gorgomite=false
    B:forestmobs.trent=false
    B:infernomobs.lobber=false
    B:junglemobs.vespid=false
    B:junglemobs.vespidqueen=false
    B:mountainmobs.troll=false
    B:plainsmobs.roc=false
    B:saltwatermobs.raiko=false
    B:shadowmobs.geist=false
    B:swampmobs.ettin=false
    B:swampmobs.ghoulzombie=false
}


entitybasehealth {
    D:Blaze=20.0
    D:CaveSpider=12.0
    D:Creeper=20.0
    D:Enderman=40.0
    D:Guardian=30.0
    D:PigZombie=20.0
    D:Shulker=30.0
    D:Silverfish=8.0
    D:Skeleton=20.0
    D:Slime=1.0
    D:Spider=16.0
    D:Witch=26.0
    D:Zombie=20.0
    D:arcticmobs.wendigo=30.0
    D:arsmagica2.EarthElemental=12.0
    D:arsmagica2.ManaCreeper=20.0
    D:arsmagica2.ManaElemental=20.0
    D:demonmobs.nethersoul=5.0
    D:demonmobs.trite=5.0
    D:desertmobs.cryptzombie=25.0
    D:desertmobs.gorgomite=5.0
    D:forestmobs.trent=80.0927734375
    D:infernomobs.lobber=30.0
    D:plainsmobs.roc=15.0
    D:saltwatermobs.raiko=15.0
    D:shadowmobs.geist=15.0
    D:swampmobs.ettin=30.0
    D:swampmobs.ghoulzombie=15.0
}


general {
    I:AntiMobFarmCheckInterval=30
    B:AntiMobfarmingEnabled=true
    B:"MM_1UP enabled"=true
    B:"MM_Alchemist enabled"=true
    B:"MM_Berserk enabled"=true
    B:"MM_Blastoff enabled"=true
    B:"MM_Bulwark enabled"=true
    B:"MM_Choke enabled"=true
    B:"MM_Cloaking enabled"=true
    B:"MM_Darkness enabled"=true
    B:"MM_Ender enabled"=true
    B:"MM_Exhaust enabled"=true
    B:"MM_Fiery enabled"=true
    B:"MM_Ghastly enabled"=true
    B:"MM_Gravity enabled"=true
    B:"MM_Lifesteal enabled"=true
    B:"MM_Ninja enabled"=false
    B:"MM_Poisonous enabled"=true
    B:"MM_Quicksand enabled"=true
    B:"MM_Regen enabled"=true
    B:"MM_Rust enabled"=true
    B:"MM_Sapper enabled"=true
    B:"MM_Sprint enabled"=true
    B:"MM_Sticky enabled"=true
    B:"MM_Storm enabled"=true
    B:"MM_Vengeance enabled"=true
    B:"MM_Weakness enabled"=true
    B:"MM_Webber enabled"=true
    B:"MM_Wither enabled"=true
    S:dimensionIDBlackList=
    B:disableGUIoverlay=false
    S:droppedItemIDsElite=arsmagica2:infinity_orb-0-1,scalinghealth:HeartContainer-0-1,basemetals:copper_ingot-0-1,basemetals:silver_ingot-0-1,basemetals:tin_ingot-0-1,basemetals:nickel_ingot-0-1,basemetals:platinum_ingot-0-1,basemetals:brass_ingot-0-1,gold_ingot-0-1
    S:droppedItemIDsInfernal=arsmagica2:infinity_orb-2-1,scalinghealth:HeartContainer-0-3,diamond-0-,basemetals:invar_ingot-0-1,basemetals:mithril_ingot-0-1,basemetals:adamantine_ingot-0-1,basemetals:starsteel_ingot-0-1,basemetals:coldiron_ingot-0-1
    S:droppedItemIDsUltra=arsmagica2:infinity_orb-1-1,scalinghealth:HeartContainer-0-2,basemetals:bronze_ingot-0-1,basemetals:electrum_ingot-0-1,basemetals:cupronickel_ingot-0-1,iron_ingot-0-1,basemetals:aquarium_ingot-0-1,basemetals:steel_ingot-0-1,basemetals:lead_ingot-0-1
    I:eliteRarity=20
    I:infernoRarity=5
    D:maxOneShotDamage=10000.0
    D:mobFarmDamageThreshold=150.0
    S:mobHealthFactor=1.0
    I:ultraRarity=5
    B:useSimpleEntityClassnames=false
}


permittedentities {
    B:arcticmobs.arix=true
    B:Blaze=true
    B:CaveSpider=true
    B:Creeper=false
    B:EnderDragon=true
    B:Enderman=true
    B:Ghast=true
    B:Guardian=true
    B:LavaSlime=true
    B:PigZombie=true
    B:Shulker=true
    B:Silverfish=true
    B:Skeleton=true
    B:Slime=true
    B:Spider=true
    B:Witch=true
    B:Zombie=true
    B:arcticmobs.wendigo=true
    B:arsmagica2.DarkMage=true
    B:arsmagica2.Darkling=true
    B:arsmagica2.EarthElemental=true
    B:arsmagica2.FireElemental=true
    B:arsmagica2.Hecate=true
    B:arsmagica2.LightningGuardian=true
    B:arsmagica2.ManaCreeper=false
    B:arsmagica2.ManaElemental=true
    B:demonmobs.astaroth=true
    B:demonmobs.nethersoul=false
    B:demonmobs.trite=false
    B:desertmobs.cryptzombie=true
    B:desertmobs.gorgomite=false
    B:forestmobs.trent=true
    B:infernomobs.lobber=true
    B:junglemobs.vespid=false
    B:junglemobs.vespidqueen=true
    B:mountainmobs.troll=true
    B:plainsmobs.roc=true
    B:saltwatermobs.raiko=true
    B:shadowmobs.geist=false
    B:swampmobs.ettin=true
    B:swampmobs.ghoulzombie=true
}

**Comment by Lycanite** [comment]
So other Lycanites Mobs are working except for just the Arix?

**Comment by Demiosis** [comment]
In this list all of these works minus the arix. But if I would put any other of your mobs in this list they won't work. For example, if i put the Belph in he wont become infernal.

**Comment by Lycanite** [comment]
I can't find any reason on my end why this will not work as the Arix's id is arcticmobs.arix, you may need to report this to infernalmobs. I'll double check a few things but it should all be good.
