### ISSUE TITLE
Server crash on load

### ISSUE THREAD

**Issue by frenzye** [Lycanite/LycanitesMobs#218]
after updating to 1.16.2.2 I started getting https://gist.github.com/frenzye/2e3e76f30cd8d469e4259768f0638caf on load

reverting to 1.16.2.1 resolved

MC1.10.2 Forge 12.18.3.2422

**Comment by Lycanite** [comment]
Please redownload 1.16.2.2, I released a bugged copy earlier which also had 1.16.2.1 packaged inside it! See #219
