### ISSUE TITLE
Crash when initializing game on 1.11.2

### ISSUE THREAD

**Issue by LemonJamTart** [Lycanite/LycanitesMobs#219]
I continually receive an initialization error while starting up the game when using version 1.16.2.2. The error report is as follows:

Error: java.lang.IllegalArgumentException: Multiple entries with same key: arcticmobs=FMLMod:arcticmobs{1.16.2.1 - MC 1.11.2} and arcticmobs=FMLMod:arcticmobs{1.16.2.2 - MC 1.11.2}

I am unsure what could be causing this, as it was a fresh install of minecraft with only Lycanite's installed.

**Comment by kinggoesgaming** [comment]
Seemingly you have two Arctic mobs mods in the jar file

**Comment by LemonJamTart** [comment]
Well, @kinggoesgaming , I don't know exactly how to fix that, and Lycanite's installs as only a single .jar file in the mod folder. Would you happen to have any ideas on how to fix that, yourself?

**Comment by Lycanite** [comment]
Yeah sorry about that one, when I renamed the main package from lycanite to com it still cached had lycanite perfectly cached so when I went to build it included both com and lycanite resulting it 1.16.2.2 and 1.16.2.1 being packaged together!

**Comment by kinggoesgaming** [comment]
@Lycanite using eclipse I assume?

**Comment by Lycanite** [comment]
Nope IntelliJ Idea, Eclipse feels too old and clunky. It all goes through gradle I think so something there I guess.

**Comment by kinggoesgaming** [comment]
Ah.. Eclipse has problems with refactoring so I assumed... Also intellij has the minecraft dev plugin if you don't have it

**Comment by Lycanite** [comment]
Oooh I should check that plugin out thanks for the tip!
Yeah Idea didn't do a good job with the refactor had to manually go over a few things and ended up using a mass find and replace in Atom. XD
