### ISSUE TITLE
[Possible][Beastiary] Entries Not Showing

### ISSUE THREAD

**Issue by Ffejrey** [Lycanite/LycanitesMobs#220]
I can rt-click on the mobs and am told they are added, but they are not there.
do this again gets me the message that I already know everything about that creature/
again they do not show up. Am I missing something, a config setting or such?
LycanitesMobsComplete 1.16.2.0 [1.10.2]
LunatriusCore-1.10.2-1.1.2.38-universal
thought these were the latest, i'll have to check again
edit: yep im a couple of vrs. behind. i'll see if the 1.16.2.2 does the same

**Comment by Lycanite** [comment]
Let me know how 1.16.2.2 goes, I have made a few changes there lately.

**Comment by Lycanite** [comment]
I'm going to close this issue for now, if the problem persists in the latest versions please open a new issue for this bug.
