### ISSUE TITLE
1.12.1 - Version Request!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lycanite/LycanitesMobs#224]
I love your mod but it took to long to get fixes for 1.10.2 and I have moved on to 1.12.1 could you push a 1.12.1 release?

**Comment by Lycanite** [comment]
1.12 will happen but I'm working on content and fixes for 1.10/1.11 first, once that's all done I'll move to 1.12, otherwise maintaining 1.10, 1.11 and 1.12 would be hell.

**Comment by P3rf3ctXZer0** [comment]
@Lycanite I understand. I will admit I love your mod so much I will foolishly stay on 1.10.2 just to use it again. Its just all major devs like the creator of pokecube @Thutmose have moved on and it makes it difficult for me to deny the latest of their mods. Even the Creator of Biomes O Plenty has moved forward!

**Comment by Lycanite** [comment]
Fear not, I'll be upgrading very soon once these new features are all finished. :D

**Comment by P3rf3ctXZer0** [comment]
@Lycanite you really are one of my favorite mod authors :)

**Comment by Lycanite** [comment]
Thanks man!
