### ISSUE TITLE
[Rendering] Tall Mob Clipping

### ISSUE THREAD

**Issue by Lycanite** [Lycanite/LycanitesMobs#227]
Large mobs such as the Strider, Thresher, demon bosses, etc will disappear from when when the player is looking up so far, I need to find where Minecraft is doing this so I can stop it.

**Comment by kinggoesgaming** [comment]
I don't think you do much about that
 It's kinda hard wired for rendering performance

**Comment by Lycanite** [comment]
Damn, in 1.7.10 it wasn't a problem, but in 1.9+ it looks like theirs a method for the render bounding box but that just seems to be ignored.

**Comment by Lycanite** [comment]
Fixed in Minecraft 1.12.2!
