### ISSUE TITLE
[AI] Bottom Dwelling

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#229]
The Lacedon, Dweller, Strider, Ika, and Herma all use the free-swimming AI instead of the bottom-dwelling AI, and always spaz out whenever they are hit. The Skylus and Gorger, while supposed to use the free-swimming AI, also spaz out when hit, and the former disappears when its shell is broken underwater.

For the AI itself, while the Lacedon, Dweller, Strider, and Ika should all use the traditional bottom-dwelling AI, the Herma itself should just sink to the seafloor (without swimming up) and gain a speed buff.

**Comment by Lycanite** [comment]
Yeah the main problem was the 1.9 pathing, while it made pure underwater mobs and flying mobs great by giving them new pathing, I broke the hybrids, I need to go over my custom move helpers and navigators, clean them up and fix this issue.

**Comment by PCAwesomeness** [comment]
Oh, can I add one more creature?

**Comment by Lycanite** [comment]
Yeah sure, I'll be going over all of the pathing though which is shared by every creature anyway.

**Comment by Lycanite** [comment]
1.17.0.1 is a brand new pathing system which fixes a lot of problems, if there are more problems with the new system then open up a new issue and I shall investigate.
I've changed this task to be only about the bottom dwelling as it still isn't quite working with these mobs.

**Comment by Lycanite** [comment]
The wander AI needs to be looked at to ensure that it is respecting entity wander point modifications.

**Comment by Lycanite** [comment]
Will be fixed in the upcoming 1.17.0.2 update. Additionally bottom dwellers will now try to relocate themselves to the ground when spawned.
