### ISSUE TITLE
[Bug] Raiko needs to stop dismounting you when it dives

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#230]
I mean, diving into the water is its shtick, right? So, why would you automatically dismount it when it dives?

**Comment by Lycanite** [comment]
This makes sense, will fix it next update! :D

**Comment by Lycanite** [comment]
I should also give it a dive animation too!

**Comment by Lycanite** [comment]
I still need to add a dive animation, but it should work underwater now in 1.17.0.1!
