### ISSUE TITLE
[Pickup] Player Movement Flickering When In Block

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#232]
Rocs and Raiko sometimes glitch (the player) out when they pick up players, and Rocs refuse to drop their prey, even if they're flying 5 blocks above the ground

Striders also sometimes glitch (you) out when they snatch you.

The Skylus is the only raptorial mob that doesn't glitch out when it's attacking you; ironically enough, it also doesn't disappear when its shell is broken while it's busy eating you.

**Comment by Lycanite** [comment]
I've updated the title, so essentially:
Rocs aren't dropping.
The player glitches out, what happens exactly here, I've ran some tests in single plan and on a dedicated server and it seems ok but I should run more tests to be certain.

**Comment by Lycanite** [comment]
The Rocs not dropping will be fixed in the upcoming 1.17.0.2 update.
The player glitching seems to be when they are placed inside a block when picked up, I'm not sure what to do about this just yet.

**Comment by PCAwesomeness** [comment]
BTW, Raiko also do not drop the player unless they are above water. However, as the Raiko is a seafaring aerial predator, their inability to drop the player onto dry land does not matter as much as it does with the Roc.

**Comment by PCAwesomeness** [comment]
Alright, Raiko seem to be all good.

Rocs can also drop players again, but it takes them a long time to do so; I find this weird, as they seem to drop mobs instantaneously more often than not.

**Comment by Lycanite** [comment]
Yeah so currently the Roc will check every 5 seconds if it's 8 blocks or less from the ground, if so it then has a 50% chance to drop the player. I'll increase the rate of this check to every second next update.
When carrying the non-player, the Roc does the same but doesn't care how high it is flying thus it drops non-players a lot more frequently. You can view this log here too: https://github.com/Lycanite/LycanitesMobs/blob/master/src/main/java/com/lycanitesmobs/plainsmobs/entity/EntityRoc.java#L136

**Comment by Lycanite** [comment]
this.ticksExisted % 100 Means every 5 seconds and this.getRNG().nextBoolean() randomly returns true or false (50% chance).

**Comment by Lycanite** [comment]
Added a partial fix in 1.17.0.3, the pickup offset (under the Roc's claw for example) is set to 0x0x0 if the offset would put the picked up player inside a solid block. This still wont be perfect but should help.

**Comment by Lycanite** [comment]
It seems things are still buggy here, I'm going to revert the pickup changes and instead try and force the mob to not put the player in the ground instead. I may also look at sending off player movement packets as these are used by the Roa and Thresher effectively.

**Comment by Lycanite** [comment]
Fixed in upcoming 1.17.0.7 by enabling noclip.
