### ISSUE TITLE
[Possible][Rendering?] Skylus Disappear On Low Health

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#236]
Thank you for fixing the twitching issue! 

However, Skylus still disappear whenever they're on low health and in the water.

**Comment by Lycanite** [comment]
I can't replicate this, it just loses its shell, does the whole entity just vanish forever or does it become invisible and is this for 1.11.2?

**Comment by PCAwesomeness** [comment]
Alright, they seem to be alright without their shell for a while, but they vanish as soon as they start moving.

Also, they completely despawn.

**Comment by Lycanite** [comment]
Hmm that's really odd, the shell loss is just a client side effect that re-scales the shell mesh group to 0x0x0 to hide it, server side it increases this speed, I'm wondering if that and maybe the old pathing could cause weirdness. Does this happen in 1.17.0.2 also?

**Comment by Lycanite** [comment]
I'm going to close this issue as I can't replicate it and there have been various changes, if the problem persists please open up a new issue.
