### ISSUE TITLE
Raiko do not inflict Weight on their prey

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#237]
I know this should have been reported earlier, but Raiko don't seem to inflict the Weight effect on their victims when dropping them.

In addition to this, Weight doesn't affect your ability to jump for some reason. It was fine last update (I got in a fight with a Wildkin during that time), but now, it doesn't seem to work.

**Comment by Lycanite** [comment]
Did you have the strength buff, as weight is countered by that now, weight seems to be working fine on its own for me. There is a subtle jump but not a full jump.
Can confirm Raiko aren't applying weight, will fix it next update.

**Comment by Lycanite** [comment]
Ah the Raiko was still using its own pickup entity variable instead of the shared one added in an update, easy fix for the next update (1.17.0.3), will release this tomorrow.

**Comment by PCAwesomeness** [comment]
Ah, I did eat a Battle Burrito when trying to test it.

Thank you!

**Comment by Lycanite** [comment]
No probs! There was indeed a bug with the Raiko also so thanks for letting me know!
