### ISSUE TITLE
[Mob] Concapedes Segments Broken

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#240]
Whenever I spawn a Concapede, it only spawns as a head and one extra segment. As well as this, all the segments move in a super-stringy manner (shaking in all directions and orienting itself in front of the head), and the head itself just seems to walk sideways (and backwards) spin around everytime it stops walking.

**Comment by Lycanite** [comment]
I shall take a look into them!

**Comment by Lycanite** [comment]
Fixed in 1.17.0.6!
