### ISSUE TITLE
Server crash ticking entity 

### ISSUE THREAD

**Issue by frenzye** [Lycanite/LycanitesMobs#241]
https://gist.github.com/frenzye/d869770ebd4968ff4fe7afb8dcf8b8a2

https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/376

**Comment by Keridos** [comment]
Do not think OMT has to do something with this crash. The last mod that had something in the stacktrace was this mod here.

**Comment by Lycanite** [comment]
This has been fixed in 1.17.0.4: http://lycanitesmobs.com/update/1.17.0.4 :)

**Comment by Keridos** [comment]
Thanks for the quick fix 👍
