### ISSUE TITLE
[Model] Raiko Walking Y Offset, Wing Flip

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#242]
Perhaps you can offset the model a little further down so it doesn't float above the ground when walking? Either that, or make the legs a little longer and allow them to bend when it starts flying.

Also, I'd imagine the wings would fold in the same direction that the body points, with the feathers facing upwards.

This also might be useful for Rocs.

**Comment by Lycanite** [comment]
Shouldn't be too tricky to fix up. :D

**Comment by PCAwesomeness** [comment]
Alright!

Will the player offset be moved down as well?

**Comment by Lycanite** [comment]
Sorted in 1.17.0.7.
