### ISSUE TITLE
[Mounts] Swimming Problems

### ISSUE THREAD

**Issue by PCAwesomeness** [Lycanite/LycanitesMobs#243]
Now, they just sink like any other rideable mob.

**Comment by Lycanite** [comment]
I think I'm going to make it so that all mounts can swim properly as currently they take control back but then don't work correctly, instead they'll swim underwater by player control except non-swimming mounts will move very slowly.

**Comment by Lycanite** [comment]
Will be fixed in 1.17.0.7.
