### ISSUE TITLE
Ticking Entity Server Crash

### ISSUE THREAD

**Issue by Giggitybyte** [Lycanite/LycanitesMobs#245]
I've been having this happen several times on my server with my friends. It's seems to be different mobs from this mod.  I keep having to manually delete the entities within that chunk with MCEdit. It's time consuming and annoying. I really enjoy this mod and really don't want to have to remove it.

A few crashlogs: 
https://hastebin.com/ohanayofok.txt
https://hastebin.com/ocehadorec.txt
https://hastebin.com/ehozigiwuy.txt

**Comment by Lycanite** [comment]
It looks like a problem with Better Survival that is triggered by Lycanites Mobs, I recommend sending the error to the dev of that mod, if they need me to do anything just let me know and I'll change whatever is needed.
