### ISSUE TITLE
Error - MC-1.12.2 Forge 94 -Messing With Air block State

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lycanite/LycanitesMobs#248]
The only mod present is Lycanites
https://gist.github.com/P3rf3ctXZer0/51e13fd77b38ca64e3cfe4f74d8a064a

I realize the error has nothing to do directly with Lycanites however from what I debugged the error requires Lycanites to be present to take effect. I have down to only having Lycanites present to be seen.

**Comment by Lycanite** [comment]
Ah yes I have noticed this, I'll look into fixing it.

**Comment by Lycanite** [comment]
Will be fixed in 1.17.1.3.
