### ISSUE TITLE
Grammer Nazi - MC-1.12.2 Forge 512

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lycanite/LycanitesMobs#249]
![2017-10-11 18_52_41-lycanites mobs 1 17 2 1 - files - lycanites mobs - mods - projects - minecraft c](https://user-images.githubusercontent.com/10351221/31472649-93fbe718-aeb5-11e7-99f8-409446077f3a.png)

**Comment by Lycanite** [comment]
Lol thanks I've fixed it! XD
I type so many update notes out in such as rush lol!
