### ISSUE TITLE
[1.12.2] Geonach Spawning in Nether & The End

### ISSUE THREAD

**Issue by Morpheus1101** [Lycanite/LycanitesMobs#267]
I have the below config set for mountain mobs and yet im finding that for some reason Geonach spawning in The End and Nether.
#
"group settings" {
    # Sets which biomes this mob spawns in using Biome Tags. Multiple entries should be comma separated and can be subtractive if provided with a - in front.
    S:"Mountain Mobs Spawn Biomes"=MOUNTAIN
    S:"Mountain Mobs Spawn Dimensions"=-1,1

    # If true, the 'Spawn Dimensions' list will act as a whitelist instead of a blacklist.
    B:"Mountain Mobs Spawn Dimensions Whitelist Mode"=false
}

**Comment by Lycanite** [comment]
As of the latest 1.12.2 updates, Geonach use the new ore.json spawner which ignores biomes and dimensions, you will need to add a new world restriction to it.
Replace everything in the config/lycanitesmobs/spawners/ore.json with this:
`{
	"name": "ore",
	"type": "spawner",
	"enabled": true,
	"loadDefault": false,
	"mobCount": 1,
	"ignoreDimensions": true,
	"ignoreBiomes": true,
	"ignoreCollision": true,
	"ignoreLightLevel": true,
	"ignoreForgeCanSpawnEvent": true,
	"blockBreakRadius": 1,
	"conditions": [
		{
			"type": "world",
			"dimensionIds": [0],
			"dimensionListType": "whitelist"
		}
	],
	"triggers": [
		{
			"type": "ore",
			"chance": 0.02
		}
	],
	"locations": [
		{
			"type": "base",
			"rangeMin": [0, 0, 0],
			"rangeMax": [0, 0, 0],
			"sorting": "random"
		}
	],
	"mobSpawns": [
		{
			"mobId": "mountainmobs.geonach",
			"weight": 8
		},
		{
			"mobId": "desertmobs.gorgomite",
			"weight": 2
		}
	]
}`

**Comment by Morpheus1101** [comment]
ok, thankyou for the information.
