### ISSUE TITLE
Aglebemu poisons and attacks on a very high distance(probably 10 blocks or that)

### ISSUE THREAD

**Issue by MadRatSRP** [Lycanite/LycanitesMobs#273]

**Comment by MadRatSRP** [comment]
Also that frog moves with incredible speed xd

**Comment by MadRatSRP** [comment]
Somehow it attacks in range, not in melee and poisons player

**Comment by MadRatSRP** [comment]
If its not bugged, can u nerf it a little? Its very hard to do something while that creature spawns near your home.

**Comment by Lycanite** [comment]
I'll look into nerfing it a bit, it has a long range tongue melee attack, I'll look at lowering how frequently it attacks.

**Comment by Lycanite** [comment]
In the mean time you can try setting their haste stat to 0.5 in the swampmobs-general.cfg config.

**Comment by Lycanite** [comment]
I've halved their attack rate and lowered their attack range by 25% in 1.17.3.11.

**Comment by MadRatSRP** [comment]
Thank you.
