### ISSUE TITLE
[Spawner] MobSpawn Ignores Mob Enabled Config Setting

### ISSUE THREAD

**Issue by Morpheus1101** [Lycanite/LycanitesMobs#276]
When mining Geonach spawn as they are enabled, however i am still getting the breaking blocks and for a split second seeing a gorgomite spawn and then get removed instantly as i have them disabled.

To my understanding by having the mob disabled from spawning they should not trigger this

Lycan v1.17.3.6
Forge *.1.2562

**Comment by Lycanite** [comment]
Ah it looks like the new JSON spawner MobSpawn definitions are ignoring this setting so I will fix that.
In the meantime, open config/lycanitesmobs/spawners/ore.json then set:
"loadDefault": false
"enabled": false
To completely disable the ore spawner.
You can re-enable Gorgomites and Geonach if you're happy with them spawning from other means such as events or randomly in the desert at night (Gorgomites).

**Comment by Lycanite** [comment]
Now fixed in 1.17.3.9. :D
