### ISSUE TITLE
Pull requests:2 new features

### ISSUE THREAD

**Issue by MadRatSRP** [Lycanite/LycanitesMobs#277]
Hello, what do u think about that:
1)First day monsters does not attack player at all(could be disabled in config), but then the more game lasts , the more monsters attack you more and more. They find you even at your house(somehow, xd, smell u know) and destroy blocks to get you(or just find you even in closed building(they are waiting near doors or something different)
2)Module or addon, that adds other mod drops from Lycanites creatures. For example, blizz rods from Thermal Expansion, etc.

**Comment by Lycanite** [comment]
1) With both the new (JSON 1.12.2) and old spawners (spawning config files) you can set a minimum starting day for a mob to spawn, with this you can prevent hostile mobs from spawning all together on day 1 or what not.

2) In the general configs such as swampmobs-general.cfg you can add additional drops to any mob you like too.

**Comment by MadRatSRP** [comment]
Okay, thanks for the answer.

**Comment by Lycanite** [comment]
No probs! Let me know if you have any more suggestions, they're always welcome!
