### ISSUE TITLE
[1.10] Extreme TPS and FPS lag on server

### ISSUE THREAD

**Issue by Agalyon** [Lycanite/LycanitesMobs#278]
Version 1.17.1.2   MC 1.10.2
Hello, I recently started using lycanites mobs and after significant testing in singleplayer I added the mod to my server to find that it massively reduces FPS and creates massive server lag as well. Went from on average 30ms to 70ms resting and upwards of 150ms if there is a lot going on. While there is still a significant TPS increase in singleplayer, its not on this level. I also didn't notice any real FPS drop in single player, especially compared to the server, which roughly halved my FPS. I lowered the spawning search radius, turned off the on activation spawning such as breaking rocks and sleeping, lowered the tick rate of spawning and halved the global spawn rate for lycanite mobs and it made very little impact. It almost makes me think its some kind of AI issue. Any help with this is appreciated, thanks in advance.

**Comment by Lycanite** [comment]
This is fixed in 1.12.2 with the new spawner system, it's a massive job to back port to 1.10.2 though.
If you need to stay on 1.10.2 you can try disabling Silex and Ika as they tend to spawn out of control with the old spawner which was one of the biggest contributor to lag.

**Comment by Agalyon** [comment]
Alright, thanks. I might give that a shot. I assume theres no chance of a backport?

**Comment by Lycanite** [comment]
No time soon, I prefer to focus on the latest version so that I can keep moving the mod forward, back ports can hold things up at times. There's also a few minor things I'm constantly ironing out with the latest 1.12.2 updates so I'd want to get those all sorted first before a back port. The mod is open source though so anyone is welcome to give a back port a shot. :)

**Comment by Agalyon** [comment]
I see, I'll have to try it out in a 1.12 pack then. Thanks again.
