### ISSUE TITLE
Lycanite Mobs Bypassing IC2 Armor

### ISSUE THREAD

**Issue by Ghostdreamer** [Lycanite/LycanitesMobs#28]
I just wanted to say I love this mod. It adds a challenge to end-game players to be able to actually use the "cool shiny armour/weapons" and keep the chance of death high for them so they can't power roll and basically have an "I win" button. However, there is a small bug that is completely destroying the moral of a few of my players. I am not sure if this is on your part, or on the other mod's parts so I am posting in both mods locations. 

I have noticed with the default config of Lycanite, and the default config of IC2 Experimental, all of the mobs are completely bypassing the Quantum Suit (as well as other IC2 armours). With Thaumcraft, it bypasses the armour but not the shields. 

Running Lycanite 1.10.7.2, IC2-Experimental 2.2.653, Thaumcraft 4.2.1.4

Tested in Single Player Creative, when hit by a Lycanite mob the same mob deals the same amount of heart damage regardless if Quantum suit is on or not. The only reason I am thinking it might be Lycanite is because the Quantum suit does manage damage correctly for a majority of other mods. As I said, however, I am posting in both forums because I don't know who is causing it.

**Comment by Lycanite** [comment]
This can't be an issue from this mod as the mobs vanilla damage types.
