### ISSUE TITLE
[1.12.2] Calpod summoning only summons same variants

### ISSUE THREAD

**Issue by Zsashas** [Lycanite/LycanitesMobs#284]
For example, a Verdant Calpod will only summon more Verdant Calpods. Seems like there should be some variance with different rates, same as with spawning.

Disregard if intentional.

**Comment by Lycanite** [comment]
This is currently intentional, it makes the subspecies harder to deal with as they summon others with more health, however I could add a config option for this if there is demand for it.

**Comment by Zsashas** [comment]
I like it, i just wasn't sure if it was supposed to be happening. Perhaps there is a chance to summon yet stronger variants, instead of just more of the same?

**Comment by Lycanite** [comment]
Hmm I could look into that, though it might make them a bit too powerful, I'll leave them as they are for now though. Thanks for testing things like this and for posting issues though, always helpful for improving the mod. :)
