### ISSUE TITLE
[1.12.2] Some mobs don't take fall damage

### ISSUE THREAD

**Issue by Zsashas** [Lycanite/LycanitesMobs#285]
Ent, Trent, Calpods, possibly others.

Also can there be an option to rename Trent to Treant?

**Comment by Lycanite** [comment]
The Trent is now a Treant. I'm going to keep the fall damage resistance for these mobs as they sometimes drop from tall trees when spawning.

**Comment by Zsashas** [comment]
In retrospect, that makes sense, especially with the Twilight Forest.
