### ISSUE TITLE
"Keeping Entity" errors?

### ISSUE THREAD

**Issue by Zsashas** [Lycanite/LycanitesMobs#287]
[01:39:12] [Server thread/WARN]: Keeping entity infernomobs:cephignis that already exists with UUID 9bc38ff9-7ccb-4635-bea0-6f7c2df7fd01

Usually doesn't happen for a while after starting the session, but when it does the game completely freezes for a few seconds. Seems to increase in frequency the longer the game has been running.

**Comment by Zsashas** [comment]
I just saw it happen with a vanilla chicken, so it's not just your mod I guess....

**Comment by Lycanite** [comment]
Ah I think this is why I haven't looked too far into this. I'll close this for now then.
