### ISSUE TITLE
Roa cannot be killed

### ISSUE THREAD

**Issue by Zsashas** [Lycanite/LycanitesMobs#290]
Tried various vanilla tools and TiCon tools, my TheOneProbe overlay says it has no health left but it refuses to die.

**Comment by Lycanite** [comment]
Hmm very odd I'll take a look. It cold be another mod causing the problem though as Roas don't do anything special with their deaths.

**Comment by Lycanite** [comment]
I can't replicate this, which version of the mod and is it single player or on a server?

**Comment by Zsashas** [comment]
I can't even replicate half of my own issues anymore, I have no idea what's going on.

**Comment by Lycanite** [comment]
No probs, modded Minecraft can be an unpredictable beast at times!
