### ISSUE TITLE
Ocean mobs are far too eager to pursue me across dry land

### ISSUE THREAD

**Issue by Zsashas** [Lycanite/LycanitesMobs#291]
Abtu and Skylus in particular. They straight up hop out of the water and start sliding after me.

**Comment by Lycanite** [comment]
Skylus will need to be looked at, but for Abtu it's intentional as they're supposed to be recklessly aggressive.

**Comment by Lycanite** [comment]
I can't replicate this problem, which version of the mod is this in?

**Comment by Zsashas** [comment]
1.17.4.0

**Comment by Lycanite** [comment]
Can't replicate the problem with Skylus and is intended for Abtu, I'm closing this for now but opena new issue if you can catch the Skylus doing it again.

**Comment by Zsashas** [comment]
Will keep an eye on those naughty Skyluses, got it.
