### ISSUE TITLE
[Config] Option to disable Scepters and Equipment

### ISSUE THREAD

**Issue by Dragnier** [Lycanite/LycanitesMobs#294]
In the event that a modpack dev might want to only have the mobs and their meats/drops, it might be a good idea to include an overarching disable command in the default lycanitesmobs-general.cfg file which disables all of the item types mentioned in the title.

I know there is a "weapon recipes enabled" config, but it doesn't seem to affect anything and I don't see a similar one for each individual module. Also, that only covers weapons and only disables recipes.

It would be nice to have both types of setting. One that removes recipes so they can only be looted and one that completely disables the items so they don't even show up in creative or get registered.

**Comment by Lycanite** [comment]
After looking into this, in 1.12.2 this is going to be tricky as crafting recipes are defined in JSON now and just outright removing the items can also cause problems. Currently the best method is to change the recipes. The new equipment system will be easy to disable however.
