### ISSUE TITLE
Item dupe

### ISSUE THREAD

**Issue by ltybcs** [Lycanite/LycanitesMobs#301]
1) Tame chupacabra
2) Give diamond
3) Leave server and then reconnect
4) Take your diamond from the first chupacabra and from the second one that spawns on reconnect
5) Repite
(1.7.10)

**Comment by Lycanite** [comment]
Unfortunately 1.7.10 is really old now and is no longer being updated. Perhaps at some point in the future a massive back port of the latest version of the mod could be done.
