### ISSUE TITLE
Dimension Blacklist not working.

### ISSUE THREAD

**Issue by Wrethic** [Lycanite/LycanitesMobs#302]
Im using JED to create extra dimensions. I created a dimension with ID: 2. I went through and put 2 instead of GROUP after each blacklist dimension line for every lycanitemobs spawning configs as it says in the configs comment line above it. As well the gamerules for the dimension disables all mobs from spawning. Yet lycanite mobs are still spawning in that dimension. using 1.12.1.

**Comment by Lycanite** [comment]
Some mobs have their own dimension list and also some have whitelist set to true meaning it is a whitelist instead. Also some spawners override these settings such as the fire.json spawner. Adding a dimension blacklist to the spawner json files instead will be more effective. See the nether.json spawner for how to add a dimension world condition to a spawner.

**Comment by Wrethic** [comment]
Without knowing all the JSON condition choices its hard to just create one that just says nothing can spawn here. Any chances there is a turn off all type of statement for a JSON file?

**Comment by Wrethic** [comment]
-Update- I finally found where all the JSON conditions are documented. It pretty much cleared everything up.

**Comment by Lycanite** [comment]
Ah good, yeah there's a section on the website, I need to go over and organise it into sub pages or add expanders maybe.

The main thing that catches everyone is "loadDefault" this is true and causes the JSON to be reset which is needed for when I make changes to the default spawners. Setting it to false allows for changes to be made.
