### ISSUE TITLE
[1.17.5.1] Geonach's not taking damage.

### ISSUE THREAD

**Issue by Draylynn** [Lycanite/LycanitesMobs#305]
I've tried setting them on fire, attacking them with all kinds of pickaxes, modded or otherwise, swords, axes, fire sticks (Reforge), chainsaws (IC2) etc. Tried increasing the hitbox, no effect either. I'm definitely hitting them. They won't take any damage at all.
Any tips?

**Comment by Lycanite** [comment]
Hmm this is very odd, I can't replicate this, are you using default configs?

**Comment by Draylynn** [comment]
Yes. I'll keep poking around, maybe one of the other mods is interfering. >_<

**Comment by Lycanite** [comment]
Yeah I can't replicate this at all. For fire damage they are immune but they should at least go down when hit from vanilla picks. Does it have a level set?

**Comment by Lycanite** [comment]
I'm going to close this as I can't recreate the issue, there have also been some changes to Geonach's resistances in the upcoming update related to fire damage for the new Volcan mob so maybe that will help.
