### ISSUE TITLE
[Spawner] Regional Difficulty

### ISSUE THREAD

**Issue by wizard1399** [Lycanite/LycanitesMobs#306]
Hello, 
I am currently working on a skyblock modpack for mc 1.10.2. I would like to make it server friendly, but running into an issue with difficulty scaling over time. Since it is a skyblock, I want to set the difficulty so that SKY type mobs will not spawn during the first couple mc days of play. I saw that there is a config for this, but it relies on server time. 
Let me give an example that illustrates the problem. Let us assume all SKY mobs have been set to not spawn for 7 days. Start up the server and several players join and get skyblock islands started. On the 12th day after server start up, more players join the server. Since the server has already been running for 12 days these new players will have to deal with the SKY mobs before they are ready to handle them. Instead of checking mc days, could you change it to check local area difficulty? I think this would make your mod more server friendly for new players.

P.s. could you also add an altar or some block that players could set up that would block spawns in an area that do not rely on light level

**Comment by Lycanite** [comment]
Hi there!

This can be done with Player type Spawn Conditions using the "timeMin"
which is the minimum amount of time that a player must have been playing
for in seconds, where setting this to 20mins should cover two days worth of
time. You can find more info on it here: http://lycanitesmobs.com/spawners
(I need to add a contents and some anchors to this page as it's quite big
now, but if you scroll down you should find the player type).

I can also look into adding some kind of altar feature, perhaps a player
condition that checks for surrounding blocks, I'll experiment with a few
possibilities.

**Comment by xlxAciDxlx** [comment]
So I get that it'd make more work for you @Lycanite, but could there be an option to still have a global `minSpawnDays`/`minSpawnPlayerDays` config option or something of the sort? This way _all_ mobs could optionally be spawned after X days, either based on global world/server time or player days (after world days are up).

**Comment by Lycanite** [comment]
Shouldn't be too tricky to implement, I've got a fairly modular setup for these things so I'll look into it. Perhaps I could add a global json file or something.

**Comment by xlxAciDxlx** [comment]
I'd personally prefer a config option since we already have a plethora of config options and it's nice to edit a single file, but obviously, that's up to you. :)

**Comment by Lycanite** [comment]
I'll see what I can do, the advantage of a global conditions list is that it can then do anything that individual ones can do automatically.

**Comment by Lycanite** [comment]
Decided to go with the global json in the end, a bit more complex than a config but it's much easier to implement and adds a load of global condition options now too.

**Comment by wizard1399** [comment]
Glad to hear it. Will this change be coming to the mc 1.10.2 version? 

My original question was for mc 1.10.2.  I think you started the json stuff after this versison of minecraft which means I can not declare a custom spawner. Due to other limitations, I can not update the pack to mc 1.12.  I have mob properties in the pack if that helps with a work around.

**Comment by Lycanite** [comment]
Ooh sorry I forgot about the version, yeah I probably wont be updating 1.10.X or 1.11.X anymore, the recipe and forge registry changes in 1.12.X make back porting changes quite a bit of work. The per player time feature is also exclusive to the JSON system so would be a lot of work to back port on its own as well.

**Comment by wizard1399** [comment]
Could you add in a simple check of the local area difficulty to the spawner algorithm? I would think it would be a query call to minecraft, if less than a constant in the config for that spawner type, the spawn returns false and fails. I could be wrong, but could it be a case of adding another variable to check before spawn?

**Comment by Lycanite** [comment]
Wow I didn't even know regional difficulty was a thing lol! I can add support for this to the 1.12.X spawner system, for the old system it would be a bit of a job.

**Comment by Lycanite** [comment]
I should also look at experimenting with Mob Levels and Regional Difficulty as well.

**Comment by wizard1399** [comment]
Not knowing your code, I can not comment on how difficult this would be for the 1.10.2 vers. However, I can point you to the minecraft wiki page to help get you started. https://minecraft.gamepedia.com/Difficulty

**Comment by Lycanite** [comment]
Will be available next update. Additional mob levels will increased based on local area difficulty up to +10 levels, this is configurable.
