### ISSUE TITLE
Zephyrs produce very loud thunder during storms

### ISSUE THREAD

**Issue by FrozenPulse** [Lycanite/LycanitesMobs#31]
When multiple Zephyrs spawn simultaneously during thunderstorms, the combined thunder sounds produced by their spawning are very loud. At least, that's how it is for me -- I use headphones when I play, so a person using only speakers might get a different result.

There appears to be no way of lowering the volume of their thunder spawn sounds except through the Master Volume in the sound settings. Would it be possible to remove the thunder sounds from Zephyr spawns during thunderstorms, or have a config option to disable it?

My current Lycanites Mobs version is Version 1.10.8.4.
My current Forge version is 10.13.2.1230.
I am currently using a custom modpack, with about 34 mods.
I tested this mod with and without the Snowsong sound resource pack. It was loud even with the vanilla thunder sounds.

**Comment by Lycanite** [comment]
This is because Zephyrs randomly create a lightning strike when they spawn, I'll remove this in the next update which should resolve the issue, I'll then look at spawning them randomly from lightning strikes instead.

**Comment by Lycanite** [comment]
This fix has been applied now.
