### ISSUE TITLE
[1.12.2] Reiver @ Djinn causing Ticking Entity Server crashes on their ranged attacks, disabling them from spawning  causes client crashing

### ISSUE THREAD

**Issue by DarcClan** [Lycanite/LycanitesMobs#319]
[crash-2018-01-31_19.52.07-server.txt](https://github.com/Lycanite/LycanitesMobs/files/1683091/crash-2018-01-31_19.52.07-server.txt)
[crash-2018-01-31_05.27.34-server.txt](https://github.com/Lycanite/LycanitesMobs/files/1683092/crash-2018-01-31_05.27.34-server.txt)
[crash-2018-01-31_05.33.12-server.txt](https://github.com/Lycanite/LycanitesMobs/files/1683093/crash-2018-01-31_05.33.12-server.txt)

**Comment by DarcClan** [comment]
Disabling the Reiver and Djinn from spawning now keeps kicking us out of ther server with this error

Ticking player at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?] at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?] at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?] at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?] at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]Caused by: java.lang.NullPointerException at com.lycanitesmobs.core.spawner.MobSpawn.canSpawn(MobSpawn.java:271) ~[MobSpawn.class:?] at com.lycanitesmobs.core.spawner.Spawner.getMobSpawns(Spawner.java:570) ~[Spawner.class:?] at com.lycanitesmobs.core.spawner.Spawner.doSpawn(Spawner.java:415) ~[Spawner.class:?] at com.lycanitesmobs.core.spawner.Spawner.trigger(Spawner.java:333) ~[Spawner.class:?] at com.lycanitesmobs.core.spawner.trigger.SpawnTrigger.trigger(SpawnTrigger.java:122) ~[SpawnTrigger.class:?] at com.lycanitesmobs.core.spawner.trigger.TickSpawnTrigger.onTick(TickSpawnTrigger.java:80) ~[TickSpawnTrigger.class:?] at com.lycanitesmobs.core.spawner.SpawnerEventListener.onEntityUpdate(SpawnerEventListener.java:180) ~[SpawnerEventListener.class:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_363_SpawnerEventListener_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?] at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:556) ~[ForgeHooks.class:?] at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2086) ~[vp.class:?] at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?] at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?] ... 9 more

**Comment by Lycanite** [comment]
Looks like I'm using a client side only Vector 3 class by mistake, easy to fix. Will cover it with this issue here: https://github.com/Lycanite/LycanitesMobs/issues/320

**Comment by Lycanite** [comment]
I've released update 1.18.1.2 with a fix for this: http://lycanitesmobs.com/update/1.18.1.2
