### ISSUE TITLE
Localize keybinds

### ISSUE THREAD

**Issue by Adaptivity** [Lycanite/LycanitesMobs#32]
http://i.imgur.com/RlMrvOL.jpg
Code: https://github.com/Lycanite/LycanitesMobs/blob/47bac53316a9bb9589a3ca6f22c92345fbef9367/java/lycanite/lycanitesmobs/KeyHandler.java#L24-L29

**Comment by Lycanite** [comment]
Oops I forgot about localising those, I will fix it in the next update!

**Comment by Adaptivity** [comment]
Done in: https://github.com/Lycanite/LycanitesMobs/commit/1a4cbb0c20be36f95f76657ebe68e4ca6979fae6
