### ISSUE TITLE
[Server] Using Non-Server Class for Vec3 (Crash)

### ISSUE THREAD

**Issue by DarkMatterXCIX** [Lycanite/LycanitesMobs#320]
was working at first, very visually impressive mod, but then after restarting server it crashed server-side unfortunately,

https://pastebin.com/zZEkCk9H

**Comment by Lycanite** [comment]
Oops looks like I'm using the wrong Vector 3 class there, an easy fix, in the meantime I recommend trying the previous version or disabling Reivers and Djinns. Pets are broken in the lat version though in which case 1.17.7.0 is a very stable version as well but without the new dungeon feature.
Will fix this next update.

**Comment by Lycanite** [comment]
I've released update 1.18.1.2 with a fix for this: http://lycanitesmobs.com/update/1.18.1.2
