### ISSUE TITLE
Roc causing ticking entity crash on client

### ISSUE THREAD

**Issue by wizard1399** [Lycanite/LycanitesMobs#322]
Lycanites ver 1.17.1.2
Minecraft 1.10.2
Forge 12.18.3.2422

I am having some trouble with rocs 
causing ticking entity client side crash. I think the issue is the player is still being ticked after being dropped. I will upload a crash report when I can get online on something other than my phone. I was playing single player when the crash happened.

The first null pointer listed in the stacktrace is minecraft.entity.Entity.func_70068_e(Entity.java:172) and the second is 
lycanites.ExtendedEntity.updatePickedUpByEntity(ExtendedEntity.java:172)

**Comment by Lycanite** [comment]
Ah so this is a weird old bug, I do have a fix for this but it's in the latest version for 1.12.2, I recommend trying to update as I don't currently have enough free time to update older versions of the mod. You could also disable Rocs in the meantime, there might also be a config option added in plainsmobs-general.cfg where you can disable the Roc's pickup ability.

**Comment by wizard1399** [comment]
Can not update due to other mods in the pack. Will look into the configs like you suggested. Do you still want the crash log for your records?

**Comment by Lycanite** [comment]
No need for the log really, I've already got a fix for it and I think an old Git Issue has the same crash.
I might look into updating 1.10X and 1.11.X in the future, but currently 1.12.X is going through massive changes that are taking up all my time.
