### ISSUE TITLE
[Spawning] Alpha Mobs Only Spawning

### ISSUE THREAD

**Issue by MLMII** [Lycanite/LycanitesMobs#326]
Just figured I'd let you know that in deserts, only Alpha Jousts (and their subspecies) seem to be spawning, leaving them herdless.

**Comment by MLMII** [comment]
I did some testing with the newest file ( 1.19.0.2+ ) by using spawn eggs; both versions only spawn Alpha Jousts, no regular Jousts will spawn from either egg.

**Comment by MLMII** [comment]
Using the summon command also will spawn an Alpha Joust as opposed to a regular Joust.

**Comment by Lycanite** [comment]
Ah thanks for the bug report, will take a look into this, I've noticed a similar problem with Makas.

**Comment by Lycanite** [comment]
Was down to the alpha weights being to high in the new json configs, fixed next update.
