### ISSUE TITLE
Suggestion:  Increase the requirement for "lava" spawns to 3 blocks.

### ISSUE THREAD

**Issue by MLMII** [Lycanite/LycanitesMobs#328]
At current settings, lava creatures spawn inside the default blacksmith buildings in villages as they have two lava blocks, if the requirements were three lava blocks then they would be limited to lava lakes.

Thanks.

**Comment by Lycanite** [comment]
The main problem is if a lava lake is underground not far beneath the village, enough blocks will be located in the area to spawn lava mobs. Really I need to look at an efficient way to check for entire lava bodies rather than just lava blocks in an area.

**Comment by Lycanite** [comment]
On further inspection the latest update has removed block costs so I've reintroduced them at spawner level in the next update, this should also improve this.
