### ISSUE TITLE
Server world gen lag on version 1.18.1.2

### ISSUE THREAD

**Issue by DarkMatterXCIX** [Lycanite/LycanitesMobs#329]
Was the server world gen lag issue fixed? You may not know of it so i won't assume. but If not I can provide a log. i didn't provide one as of now since im away from my pc. but i checked my server and it was acting odd with that and people say when they fly or load chunks itll lag

**Comment by Lycanite** [comment]
A log would be helpful as I'm not aware of any current worldgen lag problems.

**Comment by Lycanite** [comment]
Closing as this version is pretty old now and more information is needed.

**Comment by DarkMatterXCIX** [comment]
I got your more recent versions of your mod, and it works, I don't get cascading lag as of rn, but if I get something I'll send ya a server log, thnx

**Comment by Lycanite** [comment]
Ok good to hear! I have still noticed some of these messages from time to time and I think they're triggered by spawners but only rarely, the odd message every now and then isn't that bad it just means an extra chunk has been loaded early. It gets bad when a chain reaction starts and like 50 chunks all generate at once.
