### ISSUE TITLE
[Suggestion] Dungeon Requirements

### ISSUE THREAD

**Issue by xlxAciDxlx** [Lycanite/LycanitesMobs#336]
Would it be possible to add a requirement for a certain item/items to have been picked up (or be in the player's inventory) to be able to access a dungeon? To clarify, you wouldn't be allowed in a dungeon (maybe make a specific/single entrance?) without having either picked up an item already or having that item in your inventory.

**Comment by Lycanite** [comment]
The main problem with this is that dungeons aren't protected, you can just mine in from anywhere. I might look at dungeon protection in the future though and then can easily add a locked door for this feature.

**Comment by xlxAciDxlx** [comment]
Yeah, I didn't realize the dungeons blocks were breakable. I guess that in general, not just for this feature, would be another suggestion - make the dungeon blocks unbreakable until the boss is beaten. :D Make things extra hard. Haha
