### ISSUE TITLE
still crashes 1.12.2

### ISSUE THREAD

**Issue by iplayminecraf** [Lycanite/LycanitesMobs#347]
ok i everything you said still crashes mods:  lycanites mobs  optifine HDUC 8 offline skins and moreplayermodles     crash report:

                                                     ---- Minecraft Crash Report ----

WARNING: coremods are present:
  offlineskins (OfflineSkins-1.12.2-v3a-core.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 2/21/18 2:43 PM
Description: Starting integrated server

java.lang.NullPointerException: Starting integrated server
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:67)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2367)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:67)

-- Starting integrated server --
Details:
	Level ID: New World
	Level Name: New World
Stacktrace:
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2367)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1239935992 bytes (1182 MB) / 1778384896 bytes (1696 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C8 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State       | ID                | Version              | Source                                      | Signature                                |
	|:----------- |:----------------- |:-------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAA | minecraft         | 1.12.2               | minecraft.jar                               | None                                     |
	| UCHIJAAAAAA | mcp               | 9.42                 | minecraft.jar                               | None                                     |
	| UCHIJAAAAAA | FML               | 8.0.99.99            | forge-1.12.2-14.23.1.2555.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | forge             | 14.23.1.2555         | forge-1.12.2-14.23.1.2555.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | mercurius_updater | 1.0                  | MercuriusUpdater-1.12.2.jar                 | None                                     |
	| UCHIJAAAAAA | lycanitesmobs     | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | arcticmobs        | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | demonmobs         | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | desertmobs        | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | elementalmobs     | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | forestmobs        | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | freshwatermobs    | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | infernomobs       | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | junglemobs        | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | mountainmobs      | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | plainsmobs        | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | saltwatermobs     | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | shadowmobs        | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | swampmobs         | 1.19.1.2 - MC 1.12.2 | LycanitesMobsComplete+1.19.1.2+[1.12.2].jar | None                                     |
	| UCHIJAAAAAA | moreplayermodels  | 1.12.2               | MorePlayerModels_1.12.2(18jan18).jar        | None                                     |
	| UCHIJAAAAAA | offlineskins      | 1.12.2-v3a           | OfflineSkins-1.12.2-v3a.jar                 | aaaf83332a11df02406e9f266b1b65c1306f0f76 |

	Loaded coremods (and transformers): 
offlineskins (OfflineSkins-1.12.2-v3a-core.jar)
  lain.mods.skins.asm.ASMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) CPU N2840 @ 2.16GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4276
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by xlxAciDxlx** [comment]
I don't see anything here suggesting Lycanite's Mobs is at fault or even a part of it, unless I'm missing something in the stacktrace.

**Comment by iplayminecraf** [comment]
so one of i other mods are the problem

**Comment by xlxAciDxlx** [comment]
Possibly. It's hard to say for certain since this is a generic crash - there's nothing specifically pointing to one mod, or even a mod at all. Can you confirm it without Optifine? I know some mods don't play well with it.

**Comment by Lycanite** [comment]
Yeah the crash looks very generic and doesn't mention Lycanites Mobs at all. I recommend removing each other mod until the crash stops and then investigating the mod that causes the crash.

**Comment by iplayminecraf** [comment]
hmmm  you are right optifine is the problem but im going to need to find a mod that makes my mc lag less
anyways thanks and really cool mod nice job lycanite

**Comment by iplayminecraf** [comment]
i have a suggestion add a master control for the monster helpers witch means that you can control them
like a horse or mounts and make them have armors and weapons anyways you did an awesome job lycanite

**Comment by iplayminecraf** [comment]
THIS MOD IS AMAZING JUST TRIED IT AND THE MODELS THE TEXTURES THEY ARE AMAZING LOVIN DA MOD

**Comment by xlxAciDxlx** [comment]
> im going to need to find a mod that makes my mc lag less

I recommend `FoamFix` and/or `BetterFPS`. Both have helped my FPS quite a bit, even on a high-end system.

**Comment by iplayminecraf** [comment]
thanks for the help xlxAciDxlx

**Comment by xlxAciDxlx** [comment]
No problem :)
