### ISSUE TITLE
[Creative menu] - Display bug (white windows)

### ISSUE THREAD

**Issue by Orcduxbull** [Lycanite/LycanitesMobs#352]
[
![123](https://user-images.githubusercontent.com/31479975/36698397-cd4ec730-1b5a-11e8-8c65-2168fac77378.png)
](url)

Please correct. It really hinders ... When you click on the icon on the left, the problem disappears when everything else shows itself again. The problem is in this fashion, in other modifications everything is fine.

**Comment by Lycanite** [comment]
Yeah I've noticed this for a while but it's been a lower priority but I'll take a look at it now that some performance issues and other bugs are all fixed.

**Comment by Orcduxbull** [comment]
Thank you! I'll wait)) Successful work!

**Comment by Lycanite** [comment]
Will be fixed in 1.19.3.1!
