### ISSUE TITLE
[Config] Yale Shear Item

### ISSUE THREAD

**Issue by Fireztonez** [Lycanite/LycanitesMobs#353]
Hello,
I currently work to make a long progression questing Tech and Magic modpack, and I realy like your mod. Your mod fit realy well I think in my pack, but I got a problem, when I try to shears a Yale, I obtain a block of Wool, but in my pack when I shear sheep, I optain only somes Fleece, by Better With Mods. I want to have possibility to match the result with Yale or completly disable the possibility to shears the Yale, to not break the progression, which wants to get wool take several steps

Thank's for your great work and the awesome mod!
Fireztonez

**Comment by Lycanite** [comment]
I'll look into adding a config option to change the sheared items from Yale for you. It will be added to mountainmobs-general.cfg. I'm not sure if I'll be able to make this item colorable though.

**Comment by Lycanite** [comment]
Ok added this to 1.19.3.3, you'll need to have at least one Yale spawned to generate the config entry.
Look for "Yale Shear Drop" in mountainmobs-general.cfg
There you can set it to any block or item you want (but only wool will be colored). You can also change the min and max amount dropped as well as the chance, etc.

**Comment by Fireztonez** [comment]
Thank you very mutch for adding that config!

**Comment by Lycanite** [comment]
No probs!
