### ISSUE TITLE
[Mobs] Mobs incorrectly targetting invisible or vanished players

### ISSUE THREAD

**Issue by KasperFranz** [Lycanite/LycanitesMobs#36]
The mobs isn't respecting when a player is vanished (Like the normally mobs is doing)

**Comment by Lycanite** [comment]
Hmm I'll take a look into it!

**Comment by KasperFranz** [comment]
Ty sir :)

**Comment by Lycanite** [comment]
Mobs still seem to be attacking players with the invisibility effect active in general so hopefully fixing that will fix the /vanish from other mods or Bukkit plugins.

**Comment by Lycanite** [comment]
This shold now be fixed in the upcoming 1.11.0.1 update.
