### ISSUE TITLE
[Config] Suffocation Immunity

### ISSUE THREAD

**Issue by Boolyman** [Lycanite/LycanitesMobs#360]
There are a lot of Space related mods coming out lateley, and your creatures work really well with Galacticraft, Advanced Rocketry, etc....  Unfortunately, it breaks the immersion when all of your mobs start choking and dying because there's no air in space.  Could you add an option to your configs that will allow us to make your mobs immune to suffocation?

**Comment by Lycanite** [comment]
Can do, should be simple enough to add, will look at adding this to the next update for ya!

**Comment by Lycanite** [comment]
Added in 1.19.3.5.

**Comment by Boolyman** [comment]
I'm not sure what damage type Galacticraft uses to impose suffocation, but the two toggles you put in for drowning damage and wall suffocation damage don't prevent them choking in space?  Is there anything else you may be able to try?
