### ISSUE TITLE
[Config] Nymph Life Leak (Projectiles)

### ISSUE THREAD

**Issue by Fireztonez** [Lycanite/LycanitesMobs#365]
Hello,
I see in the last update (1.19.3.5), the nymph start to give effect Life Steal, and regenerate that life very quickly. On the start of my modpack the player need to kill somes Nymph for get differenty plant's and seeds, but is realy hard really hard, without a good weapon to kill them, if have so mutch regen...

Can you help me or give a fix for that?

Minecraft 1.12.2
Lycanites 1.19.3.5
Forge 14.23.2.2629

Thank's

**Comment by Lycanite** [comment]
Hey!

There should be a setting somewhere in elementalsmobs-general.cfg that you can use. If not let me know and I'll investigate further.

**Comment by Fireztonez** [comment]
Doesn't look to have any option about that in "elementalsmobs-general.cfg"... This file contain only 6 options and only one talk about the Nymph, and is for the Healing...

**Comment by Lycanite** [comment]
Oh the Life Leak effect not the healing, I see! For that goto elements/fae.json in there you can replace the lifeleak potion effect with a different effect or just remove it. Be sure to set "loadDefault" to false and make sure the json format is valid or else the json file will reset itself.

**Comment by Fireztonez** [comment]
I change in the file and put other effect like that:
```
"debuffs": [
    "extrautils2:xu2.gravity"
  ],
```
But that setting doesn't change anything, the nymph still give the Life Leak effect... So, I think something wrong in your verification code for the effect...

**Comment by Fireztonez** [comment]
So, I do something wrong in the config or is it a problem you will need to fix?

**Comment by Lycanite** [comment]
Ah I think it's also hard coded onto the projectile itself, I'll add a config for it.

**Comment by Lycanite** [comment]
Added in 1.19.5.0.

**Comment by Fireztonez** [comment]
Thank's for add that possibility!

**Comment by Lycanite** [comment]
Hmm I could be possible that it's being applied by both the projectile and the Nymph itself, in creatures/nymph.json set "loadDefault" to false and then set "effect" to 0.

**Comment by Fireztonez** [comment]
Ok, thank's,
I will try that

**Comment by Fireztonez** [comment]
I just do what you said, and turn "effect" to 0, it works to disable the leak of life, but the effect defined in the file fea.json does not work at all ... So, this config seems completely useless ...

To test if the problem came from the potion effect I had configured (since it was an effect of a mod), which possibly could not have been supported, I changed to use "minecraft: poison". The effect is not used, no matter whether effect is set to 0 or 10...

For my pack this is not a big problem, I can probably do without any negative effects, but probably you should look for a way to take this effect, and not just use the hard-coded effect.

**Comment by Lycanite** [comment]
To confirm, did you use exactly "minecraft: poison" or "minecraft:poison" as the space would break it?

**Comment by Lycanite** [comment]
When testing I think I added '/lm effects reload' I've been trying to make configs as relaodable as possible recently. :D

**Comment by Fireztonez** [comment]
I just look to make sure, and the effect is write ok ("minecraft:poison"). I think the space come by the fact some times I write the message in Google Translate, becose my english is not perfect,
So, that's not the problem... And I try again with making the effect to 0, and I just didn't get any effect after hit the nymph...

So, the problem is still the same
Fireztonez

**Comment by Lycanite** [comment]
Oh I think I see what's happening now.
Set the Nymph's effects back to 1.
Set poison in fae.json.
Keep lifeleak disabled for faebolt.
That should do what you want.
