### ISSUE TITLE
[Spawning] Sleep Spawner Bed Block Filter

### ISSUE THREAD

**Issue by Fireztonez** [Lycanite/LycanitesMobs#369]
Hello,
I whan't in my modpack, question of make more advencement possibility, to have a way to blacklist some bed of the spawning chance of Phantom. By example, I have in my pack the Sleeping Mat from Cyclic (Realy early-game bed), and at the end, you can make a vanilla bed... So I whan't to blacklist the vanilla bed from the spawning.

I don't know if is something realy hard to made or no for you.

Fireztonez

**Comment by Lycanite** [comment]
This might be quite easy to add, I'll look into it!

**Comment by Lycanite** [comment]
Added in 1.19.5.0, uses the block filter list like other block spawn triggers. See the fire.json spawner as an example.

**Comment by Fireztonez** [comment]
Thank'you very mutch for add that option!
