### ISSUE TITLE
[Mod Interaction] Implement FlyingMob on relevant entities

### ISSUE THREAD

**Issue by ReikaKalseki** [Lycanite/LycanitesMobs#37]
Could you please implement my [FlyingMob](https://github.com/ReikaKalseki/RotaryCraft/blob/master/API/Interfaces/FlyingMob.java) interface on the entities of yours that fly? Since your entities do not extend EntityFlying, this is the only way to make RotaryCraft recognize them as flying entities (and I am starting to get bug reports about the AA gun not targeting them, among other things).

**Comment by Lycanite** [comment]
Can do! The isHostile() method matches up nicely with my EntityCreatureBase class too and I can easily hook isCurrentlyFlying() up correctly to as some mobs such as the Afrit will randomly land and walk around for a bit instead. I'll get it into the next update which I might be pushing out later today.

**Comment by Lycanite** [comment]
I've added this interface into the source for the next update, it's applied to all entities from the mod though, will that work? (All mobs can be set to fly via NBT editing and some mods such as the Apocalypse mod enable flight on high difficulty levels). isCurrentlyFlying() should report whether a mob is flying or not accurately, isHostile should also be accurate too.

**Comment by ReikaKalseki** [comment]
Yes, that should work. Where required, I actively test the return values of the two functions, not just instanceof.

Thank you. :)

**Comment by ReikaKalseki** [comment]
If possible, could you please try using @Optional or some custom derivative rather than shipping the API? Shipping it makes version control somewhat difficult.

**Comment by Lycanite** [comment]
Will do!

**Comment by Lycanite** [comment]
This is quite old now, if needed I can look at adding this or something similar on newer updates.

**Comment by ReikaKalseki** [comment]
I am still on 1.7.10.
