### ISSUE TITLE
[Drops] Invalid Fish Metadata

### ISSUE THREAD

**Issue by fandomaniac** [Lycanite/LycanitesMobs#371]
When Ioray are killed, the raw fish that are dropped are missing their texture. I'm just getting the checkered "missing texture" graphic. The Item ID with the missing texture is 0349/5

**Comment by Lycanite** [comment]
Yeah looks like the wrong metadata or something is being applied to the fish item dropping a new fish species that doesn't exist lol, will fix!

**Comment by fandomaniac** [comment]
The Thrasher also drops the same invalid fish.

**Comment by Lycanite** [comment]
Fixed in 1.19.5.0.
