### ISSUE TITLE
[Config] Option to disable Aegis aggro on chest opening (or a way to calm them down)

### ISSUE THREAD

**Issue by Geethebluesky** [Lycanite/LycanitesMobs#375]
[Gave a description](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291613-lycanites-mobs-strange-and-deadly-creatures?comment=7371) of 2 scenarios in which Aegis become aggro for unreasonable reasons, tldr: after a Ruins-generated house becomes a village, Aegis get mad at attacking my own previously-placed chest.

Second is opening chests in ruins that happen to "belong" to a village, with no villagers in proximity.

Requesting either a config flag to disable automatic aggression on opening a chest, or a way to pacify the Aegis (maybe leaving as many items in a chest as were taken out?)

**Comment by Lycanite** [comment]
I'll add a config option to disable their chest protection.
To try and fix the problem I'm going to look at them allowing players to open chests if they have positive village reputation or if no Villagers are near the Aegis.

**Comment by Lycanite** [comment]
Added in 1.19.5.0.
