### ISSUE TITLE
[AI] Bugs in follow behaviors

### ISSUE THREAD

**Issue by Kovak** [Lycanite/LycanitesMobs#381]
Quite a few places throughout code where distance is calculated as the square root of the square root

https://github.com/Lycanite/LycanitesMobs/blob/master/src/main/java/com/lycanitesmobs/core/entity/ai/EntityAIFollow.java#L72

This is causing follow behaviors to not really work

also it seems like should continue execution returns false too often causing the follow behavior to never really run, for instance:

https://github.com/Lycanite/LycanitesMobs/blob/master/src/main/java/com/lycanitesmobs/core/entity/ai/EntityAIFollow.java#L95

Here we tell it to stop executing if the mob is within stray distance however this means that the entire task will quit executing before the player ever goes beyond stray distance and actually triggers an execution of the follow behavior.

**Comment by Lycanite** [comment]
Thanks for finding these. Throughout Minecraft updates getDistance() and getDistanceSq() have constantly changed names which had led to these inconsistencies, I'll go over and correct these.

**Comment by Kovak** [comment]
So I was trying to improve the feel of the follow behavior a bit more, and I think one thing that you can do is in the shouldContinueExecuting instead of cutting off at the full follow distance, take some factor of it, I've been using:

 if(distance <= this.strayDistance / 2.0 && this.strayDistance != 0)
            return false;

This way when a mob starts running, he doesn't immediately stop as soon as he is at the outer radius. It both look like the mob is more purposefully pursuing the player and helps keep follow behavior running in cases where player is moving very actively instead of starting and stopping so frequently.

**Comment by Lycanite** [comment]
Ah very nice, I will try it out!
