### ISSUE TITLE
[AI] Null pointer issue if a player leaves server with a follower

### ISSUE THREAD

**Issue by Kovak** [Lycanite/LycanitesMobs#382]
getTarget can return null if the player has left the server during execution of the behavior here:

https://github.com/Lycanite/LycanitesMobs/blob/master/src/main/java/com/lycanitesmobs/core/entity/ai/EntityAIFollowOwner.java#L68

**Comment by Lycanite** [comment]
Is this crash happening? As getTarget() should never be null at this point due to this: https://github.com/Lycanite/LycanitesMobs/blob/master/src/main/java/com/lycanitesmobs/core/entity/ai/EntityAIFollow.java#L87

**Comment by Kovak** [comment]
oh you know what my bad on this one i caused this when i was experimenting and its not actually possible as is.

**Comment by Lycanite** [comment]
No probs! Thanks for looking into these things though!
