### ISSUE TITLE
[Item] Summoning Staffs don't take damage

### ISSUE THREAD

**Issue by Kovak** [Lycanite/LycanitesMobs#383]
chargedAttack sets portalEntity to null before the damageItemCharged is called that checks if portalEntity is null.

https://github.com/Lycanite/LycanitesMobs/blob/master/src/main/java/com/lycanitesmobs/core/item/ItemStaffSummoning.java#L155

We then set it to null again anyway in the onPlayerStopUsing i think the first set to null in charged attack can just be removed

**Comment by Lycanite** [comment]
Thanks for helping out! I'll get a fix for this one going!
