### ISSUE TITLE
[Multiplayer Issue] State Held on Item itself

### ISSUE THREAD

**Issue by Kovak** [Lycanite/LycanitesMobs#384]
Summoning Staff's hold the PortalEntity object state on the Item class itself which means there can only be one for the whole game at a time. 

This will cause problems in multiplayer if 2 people are trying to summon at the same time.

Might be a good idea to move the state to the ExtendedPlayer

**Comment by Lycanite** [comment]
Oh wow yeah that's a massive oversight on my part, not sure how that's been in there for this long! Will move it to extended player.

**Comment by Lycanite** [comment]
Will be fixed in 1.19.5.3.
