### ISSUE TITLE
[AI] Teams and Targeting

### ISSUE THREAD

**Issue by Lycanite** [Lycanite/LycanitesMobs#389]
The targeting system needs to be improved for better mod compatibility, but also just for a tidy up in general as a lot of the logic is quite old and a bit messy and does cover some cases.

So what I'll do is:
-Rely heavily on isOnSameTeam() for targeting.
-Create a string based faction name for groups like fire mobs instead of using interfaces. Perhaps later extend this into a proper faction system where vanilla or modded entities can be added to factions via configs.
-Add mount and IEntityOwnable checks to isOnSameTeam().
-The canAttackTarget() method should do simple boss checks, etc before referring to isOnSameTeam().
-The hostile towards player check should check if the target entity is able to attack the player not just if it's hostile in general and not on the same team.
-Add a config entry where comma separated player friendly entity ids can be added in addition to similar lists where needed.

https://github.com/Lycanite/LycanitesMobs/pull/388

**Comment by Kovak** [comment]
:+1: this looks like a great plan
