### ISSUE TITLE
Wrong sized hitboxes

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#39]
Abtu have a hit box thats ~1/3 or less of the whole model.
Khalks can hit you through walls. So its size is too small or too big. 
Gorgomites seems to also be smaller than the model. Hard to hit and typically hit you before you can hit them.

**Comment by Lycanite** [comment]
Thanks for reporting this, I'll go through those hitboxes and think I need to add a line of sight check to melee attacks to prevent any issues where large mobs can melee attack through walls.

**Comment by Lycanite** [comment]
This will be fixed in 1.10.11.1 coming later today.
