### ISSUE TITLE
[Config] Redundant Weapon Recipes Config

### ISSUE THREAD

**Issue by Mike-U5** [Lycanite/LycanitesMobs#398]
I set "Weapon Recipes Enabled" to false, but weapon recipes are not disabled.

-Forge 14.23.3.2673
-Lycanitesmobs 1.12.2 1.19.6.1

**Comment by Lycanite** [comment]
Ah yes I might have to remove this setting completely as you can use vanilla means to control crafting recipes now.

**Comment by Lycanite** [comment]
Will be removed next update.
