### ISSUE TITLE
[1.12.2] Mobs Spawning despite being disabled

### ISSUE THREAD

**Issue by Morpheus1101** [Lycanite/LycanitesMobs#399]
I have joust disabled in the desertmobs-general.cfg & desertmobs-spawning.cfg, but they still persist on spawning reguardless.

Forge *.3.2673
Lycanites v1.19.6.1

https://puu.sh/Abi51/d66c56b55a.png & https://puu.sh/Abi5u/0f891d3293.png

**Comment by Lycanite** [comment]
Ah those settings are old, you now have to disable in config/lycanitesmobs/creatures/joust.json instead.
