### ISSUE TITLE
[Equipment] Equipment Model JEI Crash

### ISSUE THREAD

**Issue by Jacensolo59** [Lycanite/LycanitesMobs#408]
[crash-2018-05-15_12.24.49-client.txt](https://github.com/Lycanite/LycanitesMobs/files/2005868/crash-2018-05-15_12.24.49-client.txt)

not sure what is going on, any time i look through the jei interface is causes a crash. report says soemthing about some of the equiment rendering causing a crash.

**Comment by Lycanite** [comment]
Will be fixed in 1.20.2.1.

**Comment by Jacensolo59** [comment]
awesome  ty!
