### ISSUE TITLE
Ranged mobs that have lifesteal are near impossible to kill early on.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#41]
Any mobs that have range and lifesteal are only killable if you have armor and a sword.
If you run into any of these mobs you need to try and trap them to even kill them. (Unless its a spriggan and you crit it with an axe.)

An option to change/disable the lifesteal amount would be great.

**Comment by Lycanite** [comment]
I'll incorporate this into the Effect Stat so a Spriggan with it's Effect Stat Modifier set to 0.5 will drain 50% of what it normally drains (I think it's normally 50% of damage so an Effect Stat Modifier of 0.5 will cause it to drain 25% of damage instead). This will then work with the global difficulty stat values too so you could set normal to 0.5, easy to 0.25 and hard to 1.25 if desired. By default, this means tat Easy difficulty will reduce the lifesteal of all mobs.

**Comment by Lycanite** [comment]
This will be in the next update.
