### ISSUE TITLE
[Mod Compatibility] Missing Class Exception Thaumcraft Integration

### ISSUE THREAD

**Issue by Geethebluesky** [Lycanite/LycanitesMobs#411]
This crash occurs on loading Minecraft, with the only difference in setup being versions: it crashes with 1.20.2.1 (tried with .2 as well) and not with the previous one (1.20.2.0).

    net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Lycanites Mobs (lycanitesmobs)
    Caused by: java.lang.NoClassDefFoundError: com/lycanitesmobs/core/item/ItemSoulgazer
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:516)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

[...]

[Full crashlog here](https://gist.github.com/Geethebluesky/ba7fd9d04fac80842973a49eec08dfbd),

**Comment by Morpheus1101** [comment]
Can Confirm i also recieved this crash when starting a server.

**Comment by Lycanite** [comment]
Very weird, the only difference is that in 1.20.2.1+ I added some Thaumcraft integration, it looks like the @Opional stuff might be removing the class or something causing this, I'll look into it.

**Comment by Mike-U5** [comment]
Same issue, it specifically crashes with Thaumcraft & Baubles installed.
Crashlog:

> ---- Minecraft Crash Report ----
> // Don't be sad. I'll do better next time, I promise!
> 
> Time: 5/17/18 9:40 PM
> Description: Initializing game
> 
> java.lang.NoClassDefFoundError: com/lycanitesmobs/core/item/ItemSoulgazer
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Unknown Source)
> 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:528)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
> 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: com.lycanitesmobs.core.item.ItemSoulgazer
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 39 more
> Caused by: java.lang.NoClassDefFoundError: com/lycanitesmobs/core/item/ItemBase
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(Unknown Source)
> 	at java.security.SecureClassLoader.defineClass(Unknown Source)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 41 more
> Caused by: java.lang.ClassNotFoundException: com.lycanitesmobs.core.item.ItemBase
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	... 45 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Unknown Source)
> 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:528)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
> 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_171, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 406613232 bytes (387 MB) / 603979776 bytes (576 MB) up to 2516582400 bytes (2400 MB)
> 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2400M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.3.2688 20 mods loaded, 20 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State | ID             | Version              | Source                                          | Signature                                |
> 	|:----- |:-------------- |:-------------------- |:----------------------------------------------- |:---------------------------------------- |
> 	| UC    | minecraft      | 1.12.2               | minecraft.jar                                   | None                                     |
> 	| UC    | mcp            | 9.42                 | minecraft.jar                                   | None                                     |
> 	| UC    | FML            | 8.0.99.99            | forge-1.12.2-14.23.3.2688.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UC    | forge          | 14.23.3.2688         | forge-1.12.2-14.23.3.2688.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UC    | baubles        | 1.5.2                | Baubles-1.12-1.5.2.jar                          | None                                     |
> 	| U     | lycanitesmobs  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | arcticmobs     | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | demonmobs      | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | desertmobs     | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | elementalmobs  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | forestmobs     | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | freshwatermobs | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | infernomobs    | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | junglemobs     | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | mountainmobs   | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | plainsmobs     | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | saltwatermobs  | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | shadowmobs     | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | swampmobs      | 1.20.2.2 - MC 1.12.2 | LycanitesMobsComplete+1.20.2.2+[1.12.2]-1.0.jar | None                                     |
> 	| U     | thaumcraft     | 6.1.BETA13           | Thaumcraft-1.12.2-6.1.BETA13.jar                | None                                     |
> 
> 	Loaded coremods (and transformers): 
> 	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4885' Renderer: 'Intel(R) HD Graphics 4000'
> 	Launched Version: 1.12.2-forge1.12.2-14.23.3.2688
> 	LWJGL: 2.9.4
> 	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4885, Intel
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: No
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: 
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 8x Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz

**Comment by Morpheus1101** [comment]
Yes i have Foamfix in this pack as wellas Thaumcraft & Baubles ... I also have Thaumic Periphery which adds some baubles stuff for Thaumcraft

**Comment by Geethebluesky** [comment]
Yeah I have TC, Baubles (requirement for Thaumcraft) and Foamfix 0.9.9.1.

Just tried without Foamfix, still getting the error.

**Comment by Lycanite** [comment]
If it works without Thaumcraft then I have a fix coming.
