### ISSUE TITLE
Too many mobs spawning

### ISSUE THREAD

**Issue by SheroxGG** [Lycanite/LycanitesMobs#412]
I installed this mod on my modpack and the spanw rate is exagerated like 5 monster in every chunk and it is causing other mod's mobs to despawn. I tried with the config file but it does not let me do anything to it. Help me please, Thanks!

**Comment by Geethebluesky** [comment]
In lycanitesmobs-spawning.cfg, at the bottom:

>     # Scales the spawn weights of all mobs from this mod. For example, you can use this to quickly half the spawn rates of mobs from this mod compared to vanilla/other mod mobs by setting it to 0.5.
    D:"Weight Scale"=0.5

Try changing that value to whatever else you want.

**Comment by Lycanite** [comment]
When changing any json files make sure you set "loadDefault" to false and that the json is valid otherwise it will reset the file. You can use '/lm spawners reload' whilst in game also. More info can be found here: http://lycanitesmobs.com/config

**Comment by SheroxGG** [comment]
Thanks for your help a lot but I am uninstalling the mod, I like the mod but the fact that I have to change more than 13 config files make me ill. I have to reduce the spawn rate and then reduce the spawning rate so mobs do not spawn in every chunk. If someday the mod get better I will install it again. Really thanks for your help.

**Comment by SheroxGG** [comment]
Maybe developers could add the config files to Mod options like some mods, it would be much easier.

**Comment by Lycanite** [comment]
No probs and thanks for the feedback.
I am thinking about creating a preset system at some point where a light version can be added for occasional mob spawns as well as a hardcore setting where the mobs are all massively overtuned like there were back in 1.7.10 as well.
