### ISSUE TITLE
Chupacabra move speed is to high.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#42]
When mobs movespeed get too high the AI can't keep up with how fast the entity is moving. Thus they start running circles, get stuck on things they shouldn't or the pathing is slow. (mob runs to where the player was last instead of where the player is now)

Lowering it just a bit would fix this.

**Comment by Lycanite** [comment]
I'll do some testing and perhaps looking into a way for speed up their pathing when they're chasing a player, you can lower their speed via the config if needed though.

**Comment by Lycanite** [comment]
This is to do with the mob update tick which can vary a lot depending on the client or server. I'll look into adding a config option to increase update rates of certain mobs in the future. This will be useful for bosses.
