### ISSUE TITLE
CRASH!

### ISSUE THREAD

**Issue by DarKkt** [Lycanite/LycanitesMobs#430]
I installed Lyncanitesmobs for 1.7.10 and everytime I create a world it crashes and saying this

"The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error"

I really want this mod please help.

**Comment by Lycanite** [comment]
I'll need a full error log as a NullPointerException can be caused by all kinds of mods, etc. Lycanites Mobs for 1.7.10 hasn't been updated for years now though but should be stable. Also I've moved from here to Gitlab: https://gitlab.com/Lycanite/LycanitesMobs So I recommend checking that out too.
