### ISSUE TITLE
Config on loot

### ISSUE THREAD

**Issue by ArtElleys** [Lycanite/LycanitesMobs#431]
Hi. I'm here to collect the Assembly and would like to add your mod. But as far as I remember some monsters fall ore and other valuable resources. I'd like to get that loot out somehow. The thing is, I'm building a hardcore build. And the production of metals, very negative effect on the hardcore. 1H of the mods Assembly Gregtech.

**Comment by Lycanite** [comment]
You can configure all loot drops from the creature configs at: config/lycanitesmobs/creatures
Open up a JSON file with a plain text editor.
Set "loadDefault" to false, to stop the file resetting.
Then in that file you will also find a config section that is 100% configurable.
Hope this helps! If you have more questions just leave a comment here. :)
