### ISSUE TITLE
Dup of mobs 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [Lycanite/LycanitesMobs#432]
Hello!
I found that on phantoms, you can dumb a lot of obsidian and skull skeletons-vizera. You can just stay away from the bed and at a time when you can sleep, farm phantoms.
I hope that you will do something about this.
Below is a video with this moment.
https://i.gyazo.com/18ad734ffdfd8628c36912bad0e3a859.mp4

**Comment by Lycanite** [comment]
There's supposed to be a delay before another Phantom can spawn, but looks like it's broken so I'll take a look.
I've recreated this in GitLab because GitHub is no longer being used: https://gitlab.com/Lycanite/LycanitesMobs/issues/436
