### ISSUE TITLE
Tamed Mob Health Regen

### ISSUE THREAD

**Issue by Lycanite** [Lycanite/LycanitesMobs#46]
Tamed mobs should all have very low health regeneration.
I also need to confirm a few things about max health calculation. I should ensure that subspecies have the same tamed health as regular species as they should be purely cosmetic.
Making tamed subspecies purely cosmetic is good, for example a player might just want a regular colored pet Chupacabra rather than an uncommon recolored one, but the player would be forced to use one of the subspecies due to increased health, etc which is no good, so all tamed subspecies are to be equal!

**Comment by PCAwesomeness** [comment]
It's OK. The subspecies' health drops when it becomes tamed.

**Comment by Lycanite** [comment]
Implemented in 1.11.0.0.
