### ISSUE TITLE
[Config] Default and User Configs

### ISSUE THREAD

**Issue by Lycanite** [Lycanite/LycanitesMobs#48]
There should be two copies of each config one in config/lycanitesmobs/default which acts like the config does now where it is reset every so often and one in config/lycanitesmobs/user which should never reset and should take priority over the default config.

The user configs will be blank where users will need to copy anything they want to change permanently  from the default configs over to the user configs.

**Comment by dries007** [comment]
You could also use the version system in forge and if a change is detected make a copy of the file first and tell the user that there custom config has been backed up.

**Comment by Lycanite** [comment]
Hmm that sounds interesting! I'll take a look into this!

**Comment by Lycanite** [comment]
I'm probably not going to bother with this anymore, instead I might look into a brand new config system in json format as well as config presets.
