### ISSUE TITLE
Animation API

### ISSUE THREAD

**Issue by Xee1** [Lycanite/LycanitesMobs#51]
I read in this tread that Lycanite's Mobs has a compatibility with Animation API, is right?
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289836-animationapi-animate-your-entities-v1-2-3
 @Lycanite

**Comment by Lycanite** [comment]
Lycanites Mobs wont conflict with Animation API but it doesn't use it, I was going to use it initially but never really started to do so and after a few early updates it was removed.

**Comment by Xee1** [comment]
Thanks for the answer!

**Comment by Lycanite** [comment]
No probs!
