### ISSUE TITLE
Tamed Event Mobs Despawn

### ISSUE THREAD

**Issue by Lycanite** [Lycanite/LycanitesMobs#53]
When an event spawned mob is tamed it should be 'unlinked' from the event so that it wont despawn.

**Comment by ArkavianX** [comment]
Also by extension, capture of event mobs via Safari/Jailer's nets should be unlinked as well.

**Comment by Lycanite** [comment]
I should have a fix for this now. I'm not sure how to deal with safari nets yet though...
