### ISSUE TITLE
[Request] AntiMobSpawn block/items, security for the home base

### ISSUE THREAD

**Issue by Kenshij** [Lycanite/LycanitesMobs#55]
Hello,

its hard to secure your base, animal farms or villager outposts. Magnum torches are useless on event spawning. Light level is no option.

So please create your own block / item system to prevent the spawning of any lycanite mobs to secure precious vulnerable areas.

Somthing like a "security globe" which is craftet from various lycanite monster drops or staffs, with a 3X3 chunck range lycanite spawn prevention area of effect.

That would be very cool, ist a little hard to fight fire spawning mobs in your wooden base or to see the 23x23 full grown oak tree farm/fruit farm burned down after eruption, we need security ;)

**Comment by Lycanite** [comment]
There are several options in the config that you can use to allow things such as Magnum Torches to blocks event mobs and other spawn types such as the Rock (from mining ores) type. Check out the -spawning.cfg configs and look for ignore events or something along those lines.

Let me know how that goes, I cold look into more config options where needed for you.

**Comment by Kenshij** [comment]
I can't find such lines in the configs.  Have started over with S:"Config Version"=1.10.11.2 so the config files are generated new. 
Only line to disable spawning, but i don't want to disable it, the mobs are to cool^^

**Comment by Lycanite** [comment]
Open lycanitesmobs-spawning.cfg and find the "spawner checks" section, in there set the "Ignores Event" options to true for each spawn type you want to respond to forge events (the Magnum torch uses a forge mob spawn event to block mobs from spawning).

**Comment by Kenshij** [comment]
Have found it, thx.
