### ISSUE TITLE
[Spawning] Disable mob spawning during world generation

### ISSUE THREAD

**Issue by stats** [Lycanite/LycanitesMobs#57]
Would it be desirable to have a config option to disable mob spawning when a world is generating?

When loading into the twilight forest for example you tend to find spriggans and treants everywhere.

**Comment by Lycanite** [comment]
Hmm I'll look into this, it might be tricky to do though!

**Comment by Lycanite** [comment]
I'll eventually move all mobs from Lycanites Mobs into a custom spawner which will fix this.
