### ISSUE TITLE
[Events] New Events

### ISSUE THREAD

**Issue by Lycanite** [Lycanite/LycanitesMobs#60]
Fire and Ice: Reivers an Cinders.
Afraid of The Dark: Shades
https://www.youtube.com/watch?v=dVFLhrWv84Q

**Comment by StijnSterenborg324** [comment]
Fire and Ice: Reivers, Arixes, Wendigos, Serpixes, Gorgers, Cinders, Lobbers and Afrits
Attack of the Wolfs: Maugs, Barghests and Wargs
Death Worms, Crusks, Gorgers and Serpixes

**Comment by Lycanite** [comment]
Thanks for the ideas! I'm going to be adding the new events soon, I'm currently working on a better pets and mounts system which should be awesome, it's basically familiars for everyone!
