### ISSUE TITLE
Pure lava.

### ISSUE THREAD

**Issue by Claycorp** [Lycanite/LycanitesMobs#61]
Pure lava don't make stone/cobble when touching water.
Also the light level is lower.

Is this intentional?

**Comment by Lycanite** [comment]
I'll fix the stone/cobble issue with water, it will never turn into obsidian tough as Pure Lava is renewable.
The Light Level reduction is intentional but i might change that.

**Comment by Lycanite** [comment]
Pure Lava will no convert any water it flows against into stone in the upcoming update.
