### ISSUE TITLE
Monster Spawner with Custom SpawnData Crashing Game

### ISSUE THREAD

**Issue by kamathalmighty** [Lycanite/LycanitesMobs#68]
So I've been experimenting with making dungeons and I've been using minecrafts monster spawner for a while. While it spawns mobs perfectly if I only change the entity ID, the game instantly crashes if i try to add any spawnData like health values, knockbackResistance, etc. The main error I'm getting is java.lang.NullPointerException: Loading entity NBT. Lemme know if you need crash logs although it should be easy to reproduce.

Here's an example of what I'm pasting into my command blocks:

/setblock ~ ~1 ~ minecraft:mob_spawner 0 replace {EntityId:junglemobs.vespid,SpawnData:{Attributes:[{Name:generic.maxHealth,Base:30}],HealF:30}}

**Comment by Lycanite** [comment]
I'll need a full crash log, it looks like the entity is struggling to load in the NBT data somewhere, a full log should help me pinpoint that.

**Comment by kamathalmighty** [comment]
Alright here's one of my crash reports: http://pastebin.com/dpUBTzmA

**Comment by Lycanite** [comment]
Ah I see, this'll be an easy fix!

**Comment by Lycanite** [comment]
For now, try setting a Color tag like 000000 (black), Color is currently not used yet.

**Comment by Lycanite** [comment]
This is a bit tricky it turns out, it might be related to the entity loading its NBT data without having a world object, if this is the case then the bug should be fixed next update.
