### ISSUE TITLE
Silex and Ika babies drowning/suffocating?

### ISSUE THREAD

**Issue by FrozenPulse** [Lycanite/LycanitesMobs#76]
When I breed Silex and Ika, their offspring have a tendency to die shortly after spawning. They seem to be dying by either drowning or suffocation, given that it takes some time after spawning before they start taking damage. I tried putting down glass in order to see if I could stop the possible suffocation, but it did not work. The glass I used is Managlass from the Botania mod; I believe it is transparent like vanilla glass is. Also, throwing a water breathing potion at the Silex babies did nothing to stop their drowning if that is what is causing them to die. 

Here are a few screenshots of my Ika and Silex farm setup:

http://i.imgur.com/nBN5ZXN.png
http://i.imgur.com/fQBGUu4.png
http://i.imgur.com/5qZUVkT.png

**Comment by Lycanite** [comment]
Oops I keep forgetting to fix this! What's happening is that baby Silex are so small that they slip through Minecraft's block collision I think meaning that they fall into the ground and suffocate.
I'll implement a hitbox minimum size limit to solve this.

**Comment by Lycanite** [comment]
This should be fixed in the upcoming update. I've added a hitbox minimum size limit, my tests have shown no baby Silex to fall through the ground.
