### ISSUE TITLE
[Items] High Exp Repair Costs

### ISSUE THREAD

**Issue by SnakeWildlife** [Lycanite/LycanitesMobs#80]
Example: Cinderfall Sword
Enchantments on it: Smite 4, Looting 3, Unbreakable, 3
Condition: 1326 / 1561 (almost brand new)
with 1 diamond i can repair 1326 to 1561, (235 to repair).

Enchantment Cost to repair that small amount: _37_ (huge!) 
It would be over 248 levels of enchantment cost, to repair this weapon once.
It needs HEAVILY reducing, as the costs are far too unaffordable to maintain, it would be better to make a new one than to repair the one you have, by many multiplications. In my opinion, the repair cost is unreasonable.  Love your mod! Keep up the good work :)

**Comment by Lycanite** [comment]
Oh lol I've never actually checked the repair costs of them! I'll see what I can do!

**Comment by Lycanite** [comment]
All weapons are going to be replaced with the new equipment system which wont make use of durability.
