### ISSUE TITLE
[Mob Events] Can't be prevented from spawning with Event Preventing items or Light / Torches levels.

### ISSUE THREAD

**Issue by KaneHart** [Lycanite/LycanitesMobs#95]
I thought it was better to make a new issue then keep hijacking an old one.

Here is the settings I tried and I tried with 3-4 events:
http://pastebin.com/PsdCvy6y

Here is the screenshot where you can clearly see how close to the magnum torch he spawned and the entire area is 100% lit as well.

http://i.imgur.com/L2oNbag.png

**Comment by Lycanite** [comment]
Hmm perhaps the settings you need are in the lycanitesmobs-mobevents.cfg config instead then (might be lycanitesmobs-events.cfg).

**Comment by KaneHart** [comment]
The lycanitesmobs-mobevents.cfg does not seem to have either settings. It seems that might have the ability to ignore all rules via a list that has no values inside of it.

http://pastebin.com/hJ1MkJHD

"events forced spawning" {
}

Clearly no events there meaning will not ignore other mods that effect it. So the first file seem more correct but does not seem to be actually working.

PS: This is 100% new install so no generated configs.

**Comment by Lycanite** [comment]
It looks like the config category descriptions are set to the wrong category, look for "event forced spawning" and set it all to false.

**Comment by KaneHart** [comment]
Tried that also now:
lycanitesmobs-mobevents.cfg

"event forced spawning" {
    B:arachnophobia=false
    B:bamstorm=false
    B:blackplague=false
    B:bladeflurry=false
    B:boulderdash=false
    B:cinderfall=false
    B:eruption=false
    B:halloween=false
    B:hellsfury=false
    B:marchofthegorgomites=false
    B:poopparty=false
    B:raptorrampage=false
    B:roasting=false
    B:rootriot=false
    B:rudolph=false
    B:saltytree=false
    B:satanclaws=false
    B:seastorm=false
    B:shadowgames=false
    B:subzero=false
    B:theswarm=false
    B:tsunami=false
    B:windstorm=false
    B:wingedvenom=false
    B:wintersgrasp=false
}



Still no luck. it might just not be my day :)

**Comment by Lycanite** [comment]
Hmm lol I'll have to take a look, seems like a bug!

**Comment by Lycanite** [comment]
I've looked into it, the setting needs to be true not false, give that a go, it should work from what I can see, if not then start up a new issue and I'll look further into it.
