### ISSUE TITLE
[Farmable] WorldBorder Loop

### ISSUE THREAD

**Issue by Lycanite** [Lycanite/LycanitesMobs#96]
http://pastebin.com/eDAMKT2H

Looks like a call in the Concapede Head setAge method is causing a loop of some sort.

**Comment by djoveryde** [comment]
This issue also occurs when players are running around rendering new world data and worldborder fill is off.

**Comment by Lycanite** [comment]
Will re-investigate if it occurs in 1.9 as there are a few changes that might fix this anyway.
